// src/data.ts
export interface Kana {
  char: string;
  romaji: string;
  type: 'hiragana' | 'katakana';
}

export interface Kanji {
  char: string;
  onyomi: string;
  kunyomi: string;
  meaning: string;
  type: 'kanji';
  level: 'N5' | 'N4' | 'N3' | 'N2' | 'N1';
}

export interface Kotoba {
  char: string;
  romaji: string;
  meaning: string;
  type: 'benda' | 'kerja' | 'sifat' | 'keterangan' | 'tanya' | 'percakapan' | 'seru' | 'penghubung' | 'bilangan';
}

export const kanaData: Kana[] = [
  // --- HIRAGANA ---
  // Basic (Seion) 
  { char: 'あ', romaji: 'a', type: 'hiragana' }, { char: 'い', romaji: 'i', type: 'hiragana' },
  { char: 'う', romaji: 'u', type: 'hiragana' }, { char: 'え', romaji: 'e', type: 'hiragana' },
  { char: 'お', romaji: 'o', type: 'hiragana' }, { char: 'か', romaji: 'ka', type: 'hiragana' },
  { char: 'き', romaji: 'ki', type: 'hiragana' }, { char: 'く', romaji: 'ku', type: 'hiragana' },
  { char: 'け', romaji: 'ke', type: 'hiragana' }, { char: 'こ', romaji: 'ko', type: 'hiragana' },
  { char: 'さ', romaji: 'sa', type: 'hiragana' }, { char: 'し', romaji: 'shi', type: 'hiragana' },
  { char: 'す', romaji: 'su', type: 'hiragana' }, { char: 'せ', romaji: 'se', type: 'hiragana' },
  { char: 'そ', romaji: 'so', type: 'hiragana' }, { char: 'た', romaji: 'ta', type: 'hiragana' },
  { char: 'ち', romaji: 'chi', type: 'hiragana' }, { char: 'つ', romaji: 'tsu', type: 'hiragana' },
  { char: 'て', romaji: 'te', type: 'hiragana' }, { char: 'と', romaji: 'to', type: 'hiragana' },
  { char: 'な', romaji: 'na', type: 'hiragana' }, { char: 'に', romaji: 'ni', type: 'hiragana' },
  { char: 'ぬ', romaji: 'nu', type: 'hiragana' }, { char: 'ね', romaji: 'ne', type: 'hiragana' },
  { char: 'の', romaji: 'no', type: 'hiragana' }, { char: 'は', romaji: 'ha', type: 'hiragana' },
  { char: 'ひ', romaji: 'hi', type: 'hiragana' }, { char: 'ふ', romaji: 'fu', type: 'hiragana' },
  { char: 'へ', romaji: 'he', type: 'hiragana' }, { char: 'ほ', romaji: 'ho', type: 'hiragana' },
  { char: 'ま', romaji: 'ma', type: 'hiragana' }, { char: 'み', romaji: 'mi', type: 'hiragana' },
  { char: 'む', romaji: 'mu', type: 'hiragana' }, { char: 'め', romaji: 'me', type: 'hiragana' },
  { char: 'も', romaji: 'mo', type: 'hiragana' }, { char: 'や', romaji: 'ya', type: 'hiragana' },
  { char: 'ゆ', romaji: 'yu', type: 'hiragana' }, { char: 'よ', romaji: 'yo', type: 'hiragana' },
  { char: 'ら', romaji: 'ra', type: 'hiragana' }, { char: 'り', romaji: 'ri', type: 'hiragana' },
  { char: 'る', romaji: 'ru', type: 'hiragana' }, { char: 'れ', romaji: 're', type: 'hiragana' },
  { char: 'ろ', romaji: 'ro', type: 'hiragana' }, { char: 'わ', romaji: 'wa', type: 'hiragana' },
  { char: 'を', romaji: 'wo', type: 'hiragana' }, { char: 'ん', romaji: 'n', type: 'hiragana' },

  // Voiced (Dakuon) 
  { char: 'が', romaji: 'ga', type: 'hiragana' }, { char: 'ぎ', romaji: 'gi', type: 'hiragana' },
  { char: 'ぐ', romaji: 'gu', type: 'hiragana' }, { char: 'げ', romaji: 'ge', type: 'hiragana' },
  { char: 'ご', romaji: 'go', type: 'hiragana' }, { char: 'ざ', romaji: 'za', type: 'hiragana' },
  { char: 'じ', romaji: 'ji', type: 'hiragana' }, { char: 'ず', romaji: 'zu', type: 'hiragana' },
  { char: 'ぜ', romaji: 'ze', type: 'hiragana' }, { char: 'ぞ', romaji: 'zo', type: 'hiragana' },
  { char: 'だ', romaji: 'da', type: 'hiragana' }, { char: 'ぢ', romaji: 'ji', type: 'hiragana' },
  { char: 'づ', romaji: 'zu', type: 'hiragana' }, { char: 'で', romaji: 'de', type: 'hiragana' },
  { char: 'ど', romaji: 'do', type: 'hiragana' }, { char: 'ば', romaji: 'ba', type: 'hiragana' },
  { char: 'び', romaji: 'bi', type: 'hiragana' }, { char: 'ぶ', romaji: 'bu', type: 'hiragana' },
  { char: 'べ', romaji: 'be', type: 'hiragana' }, { char: 'ぼ', romaji: 'bo', type: 'hiragana' },

  // P-Sounds (Handakuon) 
  { char: 'ぱ', romaji: 'pa', type: 'hiragana' }, { char: 'ぴ', romaji: 'pi', type: 'hiragana' },
  { char: 'ぷ', romaji: 'pu', type: 'hiragana' }, { char: 'ぺ', romaji: 'pe', type: 'hiragana' },
  { char: 'ぽ', romaji: 'po', type: 'hiragana' },

  // Yoon (Contracted Syllables) 
  { char: 'きゃ', romaji: 'kya', type: 'hiragana' }, { char: 'きゅ', romaji: 'kyu', type: 'hiragana' }, { char: 'きょ', romaji: 'kyo', type: 'hiragana' },
  { char: 'しゃ', romaji: 'sha', type: 'hiragana' }, { char: 'しゅ', romaji: 'shu', type: 'hiragana' }, { char: 'しょ', romaji: 'sho', type: 'hiragana' },
  { char: 'ちゃ', romaji: 'cha', type: 'hiragana' }, { char: 'ちゅ', romaji: 'chu', type: 'hiragana' }, { char: 'ちょ', romaji: 'cho', type: 'hiragana' },
  { char: 'にゃ', romaji: 'nya', type: 'hiragana' }, { char: 'にゅ', romaji: 'nyu', type: 'hiragana' }, { char: 'にょ', romaji: 'nyo', type: 'hiragana' },
  { char: 'ひゃ', romaji: 'hya', type: 'hiragana' }, { char: 'ひゅ', romaji: 'hyu', type: 'hiragana' }, { char: 'ひょ', romaji: 'hyo', type: 'hiragana' },
  { char: 'みゃ', romaji: 'mya', type: 'hiragana' }, { char: 'みゅ', romaji: 'myu', type: 'hiragana' }, { char: 'みょ', romaji: 'myo', type: 'hiragana' },
  { char: 'りゃ', romaji: 'rya', type: 'hiragana' }, { char: 'りゅ', romaji: 'ryu', type: 'hiragana' }, { char: 'りょ', romaji: 'ryo', type: 'hiragana' },
  { char: 'ぎゃ', romaji: 'gya', type: 'hiragana' }, { char: 'ぎゅ', romaji: 'gyu', type: 'hiragana' }, { char: 'ぎょ', romaji: 'gyo', type: 'hiragana' },
  { char: 'じゃ', romaji: 'ja', type: 'hiragana' }, { char: 'じゅ', romaji: 'ju', type: 'hiragana' }, { char: 'じょ', romaji: 'jo', type: 'hiragana' },
  { char: 'びゃ', romaji: 'bya', type: 'hiragana' }, { char: 'びゅ', romaji: 'byu', type: 'hiragana' }, { char: 'びょ', romaji: 'byo', type: 'hiragana' },
  { char: 'ぴゃ', romaji: 'pya', type: 'hiragana' }, { char: 'ぴゅ', romaji: 'pyu', type: 'hiragana' }, { char: 'ぴょ', romaji: 'pyo', type: 'hiragana' },

  // --- KATAKANA ---
  // Basic (Seion) 
  { char: 'ア', romaji: 'a', type: 'katakana' }, { char: 'イ', romaji: 'i', type: 'katakana' },
  { char: 'ウ', romaji: 'u', type: 'katakana' }, { char: 'エ', romaji: 'e', type: 'katakana' },
  { char: 'オ', romaji: 'o', type: 'katakana' }, { char: 'カ', romaji: 'ka', type: 'katakana' },
  { char: 'キ', romaji: 'ki', type: 'katakana' }, { char: 'ク', romaji: 'ku', type: 'katakana' },
  { char: 'ケ', romaji: 'ke', type: 'katakana' }, { char: 'コ', romaji: 'ko', type: 'katakana' },
  { char: 'サ', romaji: 'sa', type: 'katakana' }, { char: 'シ', romaji: 'shi', type: 'katakana' },
  { char: 'ス', romaji: 'su', type: 'katakana' }, { char: 'セ', romaji: 'se', type: 'katakana' },
  { char: 'ソ', romaji: 'so', type: 'katakana' }, { char: 'タ', romaji: 'ta', type: 'katakana' },
  { char: 'チ', romaji: 'chi', type: 'katakana' }, { char: 'ツ', romaji: 'tsu', type: 'katakana' },
  { char: 'テ', romaji: 'te', type: 'katakana' }, { char: 'ト', romaji: 'to', type: 'katakana' },
  { char: 'ナ', romaji: 'na', type: 'katakana' }, { char: 'ニ', romaji: 'ni', type: 'katakana' },
  { char: 'ヌ', romaji: 'nu', type: 'katakana' }, { char: 'ネ', romaji: 'ne', type: 'katakana' },
  { char: 'ノ', romaji: 'no', type: 'katakana' }, { char: 'ハ', romaji: 'ha', type: 'katakana' },
  { char: 'ヒ', romaji: 'hi', type: 'katakana' }, { char: 'フ', romaji: 'fu', type: 'katakana' },
  { char: 'ヘ', romaji: 'he', type: 'katakana' }, { char: 'ホ', romaji: 'ho', type: 'katakana' },
  { char: 'マ', romaji: 'ma', type: 'katakana' }, { char: 'ミ', romaji: 'mi', type: 'katakana' },
  { char: 'ム', romaji: 'mu', type: 'katakana' }, { char: 'メ', romaji: 'me', type: 'katakana' },
  { char: 'モ', romaji: 'mo', type: 'katakana' }, { char: 'ヤ', romaji: 'ya', type: 'katakana' },
  { char: 'ユ', romaji: 'yu', type: 'katakana' }, { char: 'ヨ', romaji: 'yo', type: 'katakana' },
  { char: 'ラ', romaji: 'ra', type: 'katakana' }, { char: 'リ', romaji: 'ri', type: 'katakana' },
  { char: 'ル', romaji: 'ru', type: 'katakana' }, { char: 'レ', romaji: 're', type: 'katakana' },
  { char: 'ロ', romaji: 'ro', type: 'katakana' }, { char: 'ワ', romaji: 'wa', type: 'katakana' },
  { char: 'ヲ', romaji: 'wo', type: 'katakana' }, { char: 'ン', romaji: 'n', type: 'katakana' },

  // Voiced (Dakuon) 
  { char: 'ガ', romaji: 'ga', type: 'katakana' }, { char: 'ギ', romaji: 'gi', type: 'katakana' },
  { char: 'グ', romaji: 'gu', type: 'katakana' }, { char: 'ゲ', romaji: 'ge', type: 'katakana' },
  { char: 'ゴ', romaji: 'go', type: 'katakana' }, { char: 'ザ', romaji: 'za', type: 'katakana' },
  { char: 'ジ', romaji: 'ji', type: 'katakana' }, { char: 'ズ', romaji: 'zu', type: 'katakana' },
  { char: 'ゼ', romaji: 'ze', type: 'katakana' }, { char: 'ゾ', romaji: 'zo', type: 'katakana' },
  { char: 'ダ', romaji: 'da', type: 'katakana' }, { char: 'ヂ', romaji: 'ji', type: 'katakana' },
  { char: 'ヅ', romaji: 'zu', type: 'katakana' }, { char: 'デ', romaji: 'de', type: 'katakana' },
  { char: 'ド', romaji: 'do', type: 'katakana' }, { char: 'バ', romaji: 'ba', type: 'katakana' },
  { char: 'ビ', romaji: 'bi', type: 'katakana' }, { char: 'ブ', romaji: 'bu', type: 'katakana' },
  { char: 'ベ', romaji: 'be', type: 'katakana' }, { char: 'ボ', romaji: 'bo', type: 'katakana' },

  // P-Sounds (Handakuon) 
  { char: 'パ', romaji: 'pa', type: 'katakana' }, { char: 'ピ', romaji: 'pi', type: 'katakana' },
  { char: 'プ', romaji: 'pu', type: 'katakana' }, { char: 'ペ', romaji: 'pe', type: 'katakana' },
  { char: 'ポ', romaji: 'po', type: 'katakana' },

  // Yoon (Contracted Sounds) 
  { char: 'キャ', romaji: 'kya', type: 'katakana' }, { char: 'キュ', romaji: 'kyu', type: 'katakana' }, { char: 'キョ', romaji: 'kyo', type: 'katakana' },
  { char: 'シャ', romaji: 'sha', type: 'katakana' }, { char: 'シュ', romaji: 'shu', type: 'katakana' }, { char: 'ショ', romaji: 'sho', type: 'katakana' },
  { char: 'チャ', romaji: 'cha', type: 'katakana' }, { char: 'チュ', romaji: 'chu', type: 'katakana' }, { char: 'チョ', romaji: 'cho', type: 'katakana' },
  { char: 'ニャ', romaji: 'nya', type: 'katakana' }, { char: 'ニュ', romaji: 'nyu', type: 'katakana' }, { char: 'ニョ', romaji: 'nyo', type: 'katakana' },
  { char: 'ヒャ', romaji: 'hya', type: 'katakana' }, { char: 'ヒュ', romaji: 'hyu', type: 'katakana' }, { char: 'ヒョ', romaji: 'hyo', type: 'katakana' },
  { char: 'ミャ', romaji: 'mya', type: 'katakana' }, { char: 'ミュ', romaji: 'myu', type: 'katakana' }, { char: 'ミョ', romaji: 'myo', type: 'katakana' },
  { char: 'リャ', romaji: 'rya', type: 'katakana' }, { char: 'リュ', romaji: 'ryu', type: 'katakana' }, { char: 'リョ', romaji: 'ryo', type: 'katakana' },
  { char: 'ギャ', romaji: 'gya', type: 'katakana' }, { char: 'ギュ', romaji: 'gyu', type: 'katakana' }, { char: 'ギョ', romaji: 'gyo', type: 'katakana' },
  { char: 'ジャ', romaji: 'ja', type: 'katakana' }, { char: 'ジュ', romaji: 'ju', type: 'katakana' }, { char: 'ジョ', romaji: 'jo', type: 'katakana' },
  { char: 'ビャ', romaji: 'bya', type: 'katakana' }, { char: 'ビュ', romaji: 'byu', type: 'katakana' }, { char: 'ビョ', romaji: 'byo', type: 'katakana' },
  { char: 'ピャ', romaji: 'pya', type: 'katakana' }, { char: 'ピュ', romaji: 'pyu', type: 'katakana' }, { char: 'ピョ', romaji: 'pyo', type: 'katakana' },
];

export const kanjiData: Kanji[] = [
  { char: '一', onyomi: 'ICHI, ITSU', kunyomi: 'hito(tsu)', meaning: 'one', level: 'N5', type: 'kanji' },
  { char: '二', onyomi: 'NI', kunyomi: 'futa(tsu)', meaning: 'two', level: 'N5', type: 'kanji' },
  { char: '三', onyomi: 'SAN', kunyomi: 'mit(tsu)', meaning: 'three', level: 'N5', type: 'kanji' },
  { char: '四', onyomi: 'SHI', kunyomi: 'yot(tsu), yon', meaning: 'four', level: 'N5', type: 'kanji' },
  { char: '五', onyomi: 'GO', kunyomi: 'itsu(tsu)', meaning: 'five', level: 'N5', type: 'kanji' },
  { char: '六', onyomi: 'ROKU', kunyomi: 'mut(tsu)', meaning: 'six', level: 'N5', type: 'kanji' },
  { char: '七', onyomi: 'SHICHI', kunyomi: 'nana(tsu)', meaning: 'seven', level: 'N5', type: 'kanji' },
  { char: '八', onyomi: 'HACHI', kunyomi: 'yat(tsu)', meaning: 'eight', level: 'N5', type: 'kanji' },
  { char: '九', onyomi: 'KYŪ, KU', kunyomi: 'kokono(tsu)', meaning: 'nine', level: 'N5', type: 'kanji' },
  { char: '十', onyomi: 'JŪ', kunyomi: 'tō, to', meaning: 'ten', level: 'N5', type: 'kanji' },
  { char: '百', onyomi: 'HYAKU', kunyomi: '-', meaning: 'hundred', level: 'N5', type: 'kanji' },
  { char: '千', onyomi: 'SEN', kunyomi: 'chi', meaning: 'thousand', level: 'N5', type: 'kanji' },
  { char: '万', onyomi: 'MAN', kunyomi: '-', meaning: 'ten thousand', level: 'N5', type: 'kanji' },
  { char: '水', onyomi: 'SUI', kunyomi: 'mizu', meaning: 'water', level: 'N5', type: 'kanji' },
  { char: '火', onyomi: 'KA', kunyomi: 'hi', meaning: 'fire', level: 'N5', type: 'kanji' },
  { char: '木', onyomi: 'BOKU, MOKU', kunyomi: 'ki', meaning: 'tree, wood', level: 'N5', type: 'kanji' },
  { char: '天', onyomi: 'TEN', kunyomi: 'ame, ama', meaning: 'heaven, sky', level: 'N5', type: 'kanji' },
  { char: '土', onyomi: 'DO, TO', kunyomi: 'tsuchi', meaning: 'soil, earth', level: 'N5', type: 'kanji' },
  { char: '北', onyomi: 'HOKU', kunyomi: 'kita', meaning: 'north', level: 'N5', type: 'kanji' },
  { char: '東', onyomi: 'TŌ', kunyomi: 'higashi', meaning: 'east', level: 'N5', type: 'kanji' },
  { char: '西', onyomi: 'SEI', kunyomi: 'nishi', meaning: 'west', level: 'N5', type: 'kanji' },
  { char: '南', onyomi: 'NAN', kunyomi: 'minami', meaning: 'south', level: 'N5', type: 'kanji' },
  { char: '左', onyomi: 'SA', kunyomi: 'hidari', meaning: 'left', level: 'N5', type: 'kanji' },
  { char: '右', onyomi: 'U, YŪ', kunyomi: 'migi', meaning: 'right', level: 'N5', type: 'kanji' },
  { char: '日', onyomi: 'NICHI, JITSU', kunyomi: 'hi, -bi', meaning: 'day, sun', level: 'N5', type: 'kanji' },
  { char: '月', onyomi: 'GETSU, GATSU', kunyomi: 'tsuki', meaning: 'month, moon', level: 'N5', type: 'kanji' },
  { char: '花', onyomi: 'KA', kunyomi: 'hana', meaning: 'flower', level: 'N5', type: 'kanji' },
  { char: '魚', onyomi: 'GYO', kunyomi: 'sakana', meaning: 'fish', level: 'N5', type: 'kanji' },
  { char: '空', onyomi: 'KŪ', kunyomi: 'sora', meaning: 'sky', level: 'N5', type: 'kanji' },
  { char: '山', onyomi: 'SAN', kunyomi: 'yama', meaning: 'mountain', level: 'N5', type: 'kanji' },
  { char: '川', onyomi: 'SEN', kunyomi: 'kawa', meaning: 'river', level: 'N5', type: 'kanji' },
  { char: '雨', onyomi: 'U', kunyomi: 'ame', meaning: 'rain', level: 'N5', type: 'kanji' },
  { char: '本', onyomi: 'HON', kunyomi: 'moto', meaning: 'book, origin', level: 'N5', type: 'kanji' },
  { char: '目', onyomi: 'MOKU', kunyomi: 'me', meaning: 'eye', level: 'N5', type: 'kanji' },
  { char: '口', onyomi: 'KŌ, KU', kunyomi: 'kuchi', meaning: 'mouth', level: 'N5', type: 'kanji' },
  { char: '耳', onyomi: 'JI', kunyomi: 'mimi', meaning: 'ear', level: 'N5', type: 'kanji' },
  { char: '手', onyomi: 'SHU', kunyomi: 'te', meaning: 'hand', level: 'N5', type: 'kanji' },
  { char: '足', onyomi: 'SOKU', kunyomi: 'ashi', meaning: 'foot, sufficient', level: 'N5', type: 'kanji' },
  { char: '人', onyomi: 'JIN, NIN', kunyomi: 'hito', meaning: 'person', level: 'N5', type: 'kanji' },
  { char: '母', onyomi: 'BO', kunyomi: 'haha', meaning: 'mother', level: 'N5', type: 'kanji' },
  { char: '父', onyomi: 'FU', kunyomi: 'chichi', meaning: 'father', level: 'N5', type: 'kanji' },
  { char: '女', onyomi: 'JO, NYO', kunyomi: 'onna', meaning: 'female', level: 'N5', type: 'kanji' },
  { char: '男', onyomi: 'DAN, NAN', kunyomi: 'otoko', meaning: 'male', level: 'N5', type: 'kanji' },
  { char: '子', onyomi: 'SHI, SU', kunyomi: 'ko', meaning: 'child', level: 'N5', type: 'kanji' },
  { char: '小', onyomi: 'SHŌ', kunyomi: 'chiisa(i), ko', meaning: 'small', level: 'N5', type: 'kanji' },
  { char: '中', onyomi: 'CHŪ', kunyomi: 'naka', meaning: 'middle, inside', level: 'N5', type: 'kanji' },
  { char: '大', onyomi: 'DAI, TAI', kunyomi: 'ō(kii)', meaning: 'big', level: 'N5', type: 'kanji' },
  { char: '上', onyomi: 'JŌ, SHŌ', kunyomi: 'ue, kami, a(geru)', meaning: 'above, up', level: 'N5', type: 'kanji' },
  { char: '下', onyomi: 'GE, KA', kunyomi: 'shita, sa(geru)', meaning: 'below, down', level: 'N5', type: 'kanji' },
  { char: '何', onyomi: 'KA', kunyomi: 'nani', meaning: 'what', level: 'N5', type: 'kanji' },
  { char: '行', onyomi: 'KŌ, GYŌ', kunyomi: 'i(ku)', meaning: 'go', level: 'N5', type: 'kanji' },
  { char: '見', onyomi: 'KEN', kunyomi: 'mi(ru)', meaning: 'see', level: 'N5', type: 'kanji' },
  { char: '言', onyomi: 'GEN, GON', kunyomi: 'i(u)', meaning: 'say, word', level: 'N5', type: 'kanji' },
  { char: '語', onyomi: 'GO', kunyomi: 'kata(ru)', meaning: 'language', level: 'N5', type: 'kanji' },
  { char: '食', onyomi: 'SHOKU', kunyomi: 'ta(beru), ku(u)', meaning: 'eat', level: 'N5', type: 'kanji' },
  { char: '飲', onyomi: 'IN', kunyomi: 'no(mu)', meaning: 'drink', level: 'N5', type: 'kanji' },
  { char: '会', onyomi: 'KAI', kunyomi: 'a(u)', meaning: 'meet', level: 'N5', type: 'kanji' },
  { char: '学', onyomi: 'GAKU', kunyomi: 'mana(bu)', meaning: 'study', level: 'N5', type: 'kanji' },
  { char: '休', onyomi: 'KYŪ', kunyomi: 'yasu(mu)', meaning: 'rest', level: 'N5', type: 'kanji' },
  { char: '买', onyomi: 'BAI', kunyomi: 'ka(u)', meaning: 'buy', level: 'N5', type: 'kanji' },
  { char: '闻', onyomi: 'BUN, MON', kunyomi: 'ki(ku)', meaning: 'hear', level: 'N5', type: 'kanji' },
  { char: '来', onyomi: 'RAI', kunyomi: 'ku(ru)', meaning: 'come', level: 'N5', type: 'kanji' },
  { char: '立', onyomi: 'RITSU', kunyomi: 'ta(tsu)', meaning: 'stand', level: 'N5', type: 'kanji' },
  { char: '生', onyomi: 'SEI, SHŌ', kunyomi: 'i(kiru), u(mareru), nama', meaning: 'life, raw, student', level: 'N5', type: 'kanji' },
  { char: '話', onyomi: 'WA', kunyomi: 'hana(su), hanashi', meaning: 'talk', level: 'N5', type: 'kanji' },
  { char: '出', onyomi: 'SHUTSU', kunyomi: 'de(ru)', meaning: 'exit', level: 'N5', type: 'kanji' },
  { char: '読', onyomi: 'DOKU', kunyomi: 'yo(mu)', meaning: 'read', level: 'N5', type: 'kanji' },
  { char: '入', onyomi: 'NYŪ', kunyomi: 'hai(ru), i(reru)', meaning: 'enter', level: 'N5', type: 'kanji' },
  { char: '書', onyomi: 'SHO', kunyomi: 'ka(ku)', meaning: 'write, book', level: 'N5', type: 'kanji' },
  { char: '後', onyomi: 'GO, KŌ', kunyomi: 'ato, ushi(ro)', meaning: 'after', level: 'N5', type: 'kanji' },
  { char: '古', onyomi: 'KO', kunyomi: 'furu(i)', meaning: 'old', level: 'N5', type: 'kanji' },
  { char: '高', onyomi: 'KŌ', kunyomi: 'taka(i)', meaning: 'high, expensive', level: 'N5', type: 'kanji' },
  { char: '安', onyomi: 'AN', kunyomi: 'yasu(i)', meaning: 'cheap, safe', level: 'N5', type: 'kanji' },
  { char: '多', onyomi: 'TA', kunyomi: 'oo(i)', meaning: 'many', level: 'N5', type: 'kanji' },
  { char: '新', onyomi: 'SHIN', kunyomi: 'atara(shii)', meaning: 'new', level: 'N5', type: 'kanji' },
  { char: '少', onyomi: 'SHŌ', kunyomi: 'suku(nai), suko(shi)', meaning: 'few, little', level: 'N5', type: 'kanji' },
  { char: '長', onyomi: 'CHŌ', kunyomi: 'naga(i)', meaning: 'long', level: 'N5', type: 'kanji' },
  { char: '白', onyomi: 'HAKU, BYAKU', kunyomi: 'shiro(i)', meaning: 'white', level: 'N5', type: 'kanji' },
  { char: '分', onyomi: 'FUN, BUN', kunyomi: 'wa(karu)', meaning: 'minute, understand', level: 'N5', type: 'kanji' },
  { char: '時', onyomi: 'JI', kunyomi: 'toki', meaning: 'time, hour', level: 'N5', type: 'kanji' },
  { char: '間', onyomi: 'KAN, KEN', kunyomi: 'aida, ma', meaning: 'interval', level: 'N5', type: 'kanji' },
  { char: '週', onyomi: 'SHŪ', kunyomi: '-', meaning: 'week', level: 'N5', type: 'kanji' },
  { char: '年', onyomi: 'NEN', kunyomi: 'toshi', meaning: 'year', level: 'N5', type: 'kanji' },
  { char: '今', onyomi: 'KON, KIN', kunyomi: 'ima', meaning: 'now', level: 'N5', type: 'kanji' },
  { char: '先', onyomi: 'SEN', kunyomi: 'saki', meaning: 'previous, ahead', level: 'N5', type: 'kanji' },
  { char: '前', onyomi: 'ZEN', kunyomi: 'mae', meaning: 'before', level: 'N5', type: 'kanji' },
  { char: '午', onyomi: 'GO', kunyomi: '-', meaning: 'noon', level: 'N5', type: 'kanji' },
  { char: '半', onyomi: 'HAN', kunyomi: 'naka(ba)', meaning: 'half', level: 'N5', type: 'kanji' },
  { char: '店', onyomi: 'TEN', kunyomi: 'mise', meaning: 'store', level: 'N5', type: 'kanji' },
  { char: '外', onyomi: 'GAI', kunyomi: 'soto', meaning: 'outside', level: 'N5', type: 'kanji' },
  { char: '電', onyomi: 'DEN', kunyomi: '-', meaning: 'electricity', level: 'N5', type: 'kanji' },
  { char: '道', onyomi: 'DŌ', kunyomi: 'michi', meaning: 'road', level: 'N5', type: 'kanji' },
  { char: '毎', onyomi: 'MAI', kunyomi: '-', meaning: 'every', level: 'N5', type: 'kanji' },
  { char: '友', onyomi: 'YŪ', kunyomi: 'tomo', meaning: 'friend', level: 'N5', type: 'kanji' },
  { char: '名', onyomi: 'MEI, MYŌ', kunyomi: 'na', meaning: 'name', level: 'N5', type: 'kanji' },
  { char: '金', onyomi: 'KIN, KON', kunyomi: 'kane', meaning: 'gold, money, metal', level: 'N5', type: 'kanji' },
  { char: '円', onyomi: 'EN', kunyomi: 'maru(i)', meaning: 'circle, yen', level: 'N5', type: 'kanji' },
  { char: '車', onyomi: 'SHA', kunyomi: 'kuruma', meaning: 'car', level: 'N5', type: 'kanji' },
  { char: '駅', onyomi: 'EKI', kunyomi: '-', meaning: 'station', level: 'N5', type: 'kanji' },
  { char: '気', onyomi: 'KI, KE', kunyomi: '-', meaning: 'spirit, air', level: 'N5', type: 'kanji' },
  { char: '国', onyomi: 'KOKU', kunyomi: 'kuni', meaning: 'country', level: 'N5', type: 'kanji' },
  { char: '社', onyomi: 'SHA', kunyomi: 'yashiro', meaning: 'company, shrine', level: 'N5', type: 'kanji' },
  { char: '校', onyomi: 'KŌ', kunyomi: '-', meaning: 'school', level: 'N5', type: 'kanji' },
];

// src/data.ts

export const kotobaData: Kotoba[] = [
  { char: "会う (あう)", romaji: "au", meaning: "bertemu", type: "kerja" },
  { char: "青 (あお)", romaji: "ao", meaning: "biru", type: "benda" },
  { char: "青い (あおい)", romaji: "aoi", meaning: "biru", type: "sifat" },
  { char: "赤 (あか)", romaji: "aka", meaning: "merah", type: "benda" },
  { char: "赤い (あかい)", romaji: "akai", meaning: "merah", type: "sifat" },
  { char: "明るい (あかるい)", romaji: "akarui", meaning: "terang, cerah", type: "sifat" },
  { char: "秋 (あき)", romaji: "aki", meaning: "musim gugur", type: "benda" },
  { char: "開く (あく)", romaji: "aku", meaning: "buka, terbuka", type: "kerja" },
  { char: "開ける (あける)", romaji: "akeru", meaning: "membuka", type: "kerja" },
  { char: "上げる (あげる)", romaji: "ageru", meaning: "menaikkan", type: "kerja" },
  { char: "朝 (あさ)", romaji: "asa", meaning: "pagi", type: "benda" },
  { char: "朝ごはん (あさごはん)", romaji: "asagohan", meaning: "sarapan", type: "benda" },
  { char: "明後日 (あさって)", romaji: "asatte", meaning: "lusa", type: "benda" },
  { char: "足 (あし)", romaji: "ashi", meaning: "kaki", type: "benda" },
  { char: "明日 (あした)", romaji: "ashita", meaning: "besok", type: "benda" },
  { char: "彼処 (あそこ)", romaji: "asoko", meaning: "di sana (jauh)", type: "benda" },
  { char: "遊ぶ (あそぶ)", romaji: "asobu", meaning: "bermain", type: "kerja" },
  { char: "暖かい (あたたかい)", romaji: "atatakai", meaning: "hangat (udara)", type: "sifat" },
  { char: "頭 (あたま)", romaji: "atama", meaning: "kepala", type: "benda" },
  { char: "新しい (あたらしい)", romaji: "atarashii", meaning: "baru", type: "sifat" },
  { char: "彼方 (あちら)", romaji: "achira", meaning: "di sana (sopan)", type: "benda" },
  { char: "暑い (あつい)", romaji: "atsui", meaning: "panas (udara)", type: "sifat" },
  { char: "厚い (あつい)", romaji: "atsui", meaning: "tebal", type: "sifat" },
  { char: "熱い (あつい)", romaji: "atsui", meaning: "panas (benda)", type: "sifat" },
  { char: "後 (あと)", romaji: "ato", meaning: "nanti, sesudah", type: "keterangan" },
  { char: "貴方 (あなた)", romaji: "anata", meaning: "anda, kamu", type: "benda" },
  { char: "兄 (あに)", romaji: "ani", meaning: "kakak laki-laki", type: "benda" },
  { char: "姉 (あね)", romaji: "ane", meaning: "kakak perempuan", type: "benda" },
  { char: "あの", romaji: "ano", meaning: "hmm", type: "seru" },
  { char: "アパート", romaji: "apa-to", meaning: "apartemen", type: "benda" },
  { char: "浴びる (あびる)", romaji: "abiru", meaning: "mandi", type: "kerja" },
  { char: "危ない (あぶない)", romaji: "abunai", meaning: "berbahaya", type: "sifat" },
  { char: "甘い (あまい)", romaji: "amai", meaning: "manis", type: "sifat" },
  { char: "余り (あまり)", romaji: "amari", meaning: "tidak terlalu", type: "keterangan" },
  { char: "雨 (あめ)", romaji: "ame", meaning: "hujan", type: "benda" },
  { char: "飴 (あめ)", romaji: "ame", meaning: "permen", type: "benda" },
  { char: "洗う (あらう)", romaji: "arau", meaning: "mencuci", type: "kerja" },
  { char: "有る (ある)", romaji: "aru", meaning: "ada (benda)", type: "kerja" },
  { char: "歩く (あるく)", romaji: "aruku", meaning: "berjalan", type: "kerja" },
  { char: "あれ", romaji: "are", meaning: "itu (jauh)", type: "benda" },
  { char: "いい", romaji: "ii", meaning: "bagus, baik", type: "sifat" },
  { char: "いいえ", romaji: "iie", meaning: "tidak", type: "percakapan" },
  { char: "家 (いえ)", romaji: "ie", meaning: "rumah", type: "benda" },
  { char: "行く (いく)", romaji: "iku", meaning: "pergi", type: "kerja" },
  { char: "いくつ", romaji: "ikutsu", meaning: "berapa banyak", type: "tanya" },
  { char: "いくら", romaji: "ikura", meaning: "berapa harga", type: "tanya" },
  { char: "池 (いけ)", romaji: "ike", meaning: "kolam", type: "benda" },
  { char: "医者 (いしゃ)", romaji: "isha", meaning: "dokter", type: "benda" },
  { char: "椅子 (いす)", romaji: "isu", meaning: "kursi", type: "benda" },
  { char: "忙しい (いそがしい)", romaji: "isogashii", meaning: "sibuk", type: "sifat" },
  { char: "痛い (いたい)", romaji: "itai", meaning: "sakit", type: "sifat" },
  { char: "一 (いち)", romaji: "ichi", meaning: "satu", type: "benda" },
  { char: "一日 (いちにち)", romaji: "ichinichi", meaning: "satu hari", type: "benda" },
  { char: "一番 (いちばん)", romaji: "ichiban", meaning: "paling, nomor satu", type: "keterangan" },
  { char: "一緒 (いっしょ)", romaji: "issho", meaning: "bersama", type: "keterangan" },
  { char: "何時 (いつ)", romaji: "itsu", meaning: "kapan", type: "tanya" },
  { char: "五日 (いつか)", romaji: "itsuka", meaning: "tanggal 5", type: "benda" },
  { char: "五つ (いつつ)", romaji: "itsutsu", meaning: "lima buah", type: "benda" },
  { char: "いつも", romaji: "itsumo", meaning: "selalu", type: "keterangan" },
  { char: "犬 (いぬ)", romaji: "inu", meaning: "anjing", type: "benda" },
  { char: "今 (いま)", romaji: "ima", meaning: "sekarang", type: "benda" },
  { char: "意味 (いみ)", romaji: "imi", meaning: "arti", type: "benda" },
  { char: "妹 (いもうと)", romaji: "imouto", meaning: "adik perempuan", type: "benda" },
  { char: "嫌 (いや)", romaji: "iya", meaning: "tidak suka", type: "sifat" },
  { char: "入り口 (いりぐち)", romaji: "iriguchi", meaning: "pintu masuk", type: "benda" },
  { char: "要る (いる)", romaji: "iru", meaning: "perlu", type: "kerja" },
  { char: "居る (いる)", romaji: "iru", meaning: "ada (makhluk hidup)", type: "kerja" },
  { char: "入れる (いれる)", romaji: "ireru", meaning: "memasukkan", type: "kerja" },
  { char: "色 (いろ)", romaji: "iro", meaning: "warna", type: "benda" },
  { char: "色々 (いろいろ)", romaji: "iroiro", meaning: "bermacam-macam", type: "sifat" },
  { char: "上 (うえ)", romaji: "ue", meaning: "atas", type: "benda" },
  { char: "後ろ (うしろ)", romaji: "ushiro", meaning: "belakang", type: "benda" },
  { char: "薄い (うすい)", romaji: "usui", meaning: "tipis", type: "sifat" },
  { char: "歌 (うた)", romaji: "uta", meaning: "lagu", type: "benda" },
  { char: "歌う (うたう)", romaji: "utau", meaning: "menyanyi", type: "kerja" },
  { char: "生まれる (うまれる)", romaji: "umareru", meaning: "lahir", type: "kerja" },
  { char: "海 (うみ)", romaji: "umi", meaning: "laut", type: "benda" },
  { char: "売る (うる)", romaji: "uru", meaning: "menjual", type: "kerja" },
  { char: "煩い (うるさい)", romaji: "urusai", meaning: "berisik", type: "sifat" },
  { char: "上着 (うわぎ)", romaji: "uwagi", meaning: "jaket, mantel", type: "benda" },
  { char: "絵 (え)", romaji: "e", meaning: "gambar", type: "benda" },
  { char: "映画 (えいが)", romaji: "eiga", meaning: "film", type: "benda" },
  { char: "映画館 (えいがかん)", romaji: "eigakan", meaning: "bioskop", type: "benda" },
  { char: "英語 (えいご)", romaji: "eigo", meaning: "bahasa Inggris", type: "benda" },
  { char: "ええ", romaji: "ee", meaning: "ya (santai)", type: "percakapan" },
  { char: "駅 (えき)", romaji: "eki", meaning: "stasiun", type: "benda" },
  { char: "エレベーター", romaji: "erebe-ta-", meaning: "lift", type: "benda" },
  { char: "鉛筆 (えんぴつ)", romaji: "enpitsu", meaning: "pensil", type: "benda" },
  { char: "美味しい (おいしい)", romaji: "oishii", meaning: "enak", type: "sifat" },
  { char: "多い (おおい)", romaji: "ooi", meaning: "banyak", type: "sifat" },
  { char: "大きい (おおきい)", romaji: "ookii", meaning: "besar", type: "sifat" },
  { char: "大きな (おおきな)", romaji: "ookina", meaning: "besar (keterangan)", type: "sifat" },
  { char: "お母さん (おかあさん)", romaji: "okaasan", meaning: "ibu", type: "benda" },
  { char: "お菓子 (おかし)", romaji: "okashi", meaning: "cemilan", type: "benda" },
  { char: "大勢 (おおぜい)", romaji: "oozei", meaning: "banyak orang", type: "keterangan" },
  { char: "お金 (おかね)", romaji: "okane", meaning: "uang", type: "benda" },
  { char: "起きる (おきる)", romaji: "okiru", meaning: "bangun", type: "kerja" },
  { char: "置く (おく)", romaji: "oku", meaning: "meletakkan", type: "kerja" },
  { char: "奥さん (おくさん)", romaji: "okusan", meaning: "istri (orang lain)", type: "benda" },
  { char: "お酒 (おさけ)", romaji: "osake", meaning: "sake/alkohol", type: "benda" },
  { char: "お皿 (おさら)", romaji: "osara", meaning: "piring", type: "benda" },
  { char: "教える (おしえる)", romaji: "oshieru", meaning: "mengajar", type: "kerja" },
  { char: "伯父 (おじ)", romaji: "oji", meaning: "paman", type: "benda" },
  { char: "押す (おす)", romaji: "osu", meaning: "menekan", type: "kerja" },
  { char: "遅い (おそい)", romaji: "osoi", meaning: "lambat, terlambat", type: "sifat" },
  { char: "お茶 (おちゃ)", romaji: "ocha", meaning: "teh", type: "benda" },
  { char: "お手洗い (おてあらい)", romaji: "otearai", meaning: "toilet", type: "benda" },
  { char: "お父さん (おとうさん)", romaji: "otousan", meaning: "ayah", type: "benda" },
  { char: "弟 (おとうと)", romaji: "otouto", meaning: "adik laki-laki", type: "benda" },
  { char: "男 (おとこ)", romaji: "otoko", meaning: "laki-laki", type: "benda" },
  { char: "女の子 (おんなのこ)", romaji: "onnanoko", meaning: "anak perempuan", type: "benda" },
  { char: "一昨日 (おととい)", romaji: "ototoi", meaning: "kemarin lusa", type: "keterangan" },
  { char: "大人 (おとな)", romaji: "otona", meaning: "dewasa", type: "benda" },
  { char: "お腹 (おなか)", romaji: "onaka", meaning: "perut", type: "benda" },
  { char: "同じ (おなじ)", romaji: "onaji", meaning: "sama", type: "sifat" },
  { char: "お兄さん (おにいさん)", romaji: "oniisan", meaning: "kakak laki-laki", type: "benda" },
  { char: "お姉さん (おねえさん)", romaji: "oneesan", meaning: "kakak perempuan", type: "benda" },
  { char: "お祖母さん (おばあさん)", romaji: "obaasan", meaning: "nenek", type: "benda" },
  { char: "伯母さん (おばさん)", romaji: "obasan", meaning: "bibi", type: "benda" },
  { char: "お風呂 (おふろ)", romaji: "ofuro", meaning: "bak mandi", type: "benda" },
  { char: "お弁当 (おべんとう)", romaji: "obentou", meaning: "bekal", type: "benda" },
  { char: "覚える (おぼえる)", romaji: "oboeru", meaning: "mengingat", type: "kerja" },
  { char: "お巡りさん (おまわりさん)", romaji: "omawarisan", meaning: "polisi", type: "benda" },
  { char: "泳ぐ (およぐ)", romaji: "oyogu", meaning: "berenang", type: "kerja" },
  { char: "降りる (おりる)", romaji: "oriru", meaning: "turun", type: "kerja" },
  { char: "終わる (おわる)", romaji: "owaru", meaning: "selesai", type: "kerja" },
  { char: "音楽 (おんがく)", romaji: "ongaku", meaning: "musik", type: "benda" },
  { char: "女 (おんな)", romaji: "onna", meaning: "perempuan", type: "benda" },
  { char: "会社 (かいしゃ)", romaji: "kaisha", meaning: "perusahaan", type: "benda" },
  { char: "階段 (かいだん)", romaji: "kaidan", meaning: "tangga", type: "benda" },
  { char: "買い物 (かいもの)", romaji: "kaimono", meaning: "belanja", type: "benda" },
  { char: "買う (かう)", romaji: "kau", meaning: "membeli", type: "kerja" },
  { char: "返す (かえす)", romaji: "kaesu", meaning: "mengembalikan", type: "kerja" },
  { char: "帰る (かえる)", romaji: "kaeru", meaning: "pulang", type: "kerja" },
  { char: "掛かる (かかる)", romaji: "kakaru", meaning: "memakan (waktu/biaya)", type: "kerja" },
  { char: "鍵 (かぎ)", romaji: "kagi", meaning: "kunci", type: "benda" },
  { char: "書く (かく)", romaji: "kaku", meaning: "menulis", type: "kerja" },
  { char: "掛ける (かける)", romaji: "kakeru", meaning: "memasang/menelepon", type: "kerja" },
  { char: "傘 (かさ)", romaji: "kasa", meaning: "payung", type: "benda" },
  { char: "貸す (かす)", romaji: "kasu", meaning: "meminjamkan", type: "kerja" },
  { char: "風 (かぜ)", romaji: "kaze", meaning: "angin/flu", type: "benda" },
  { char: "家族 (かぞく)", romaji: "kazoku", meaning: "keluarga", type: "benda" },
  { char: "方 (かた)", romaji: "kata", meaning: "cara/orang", type: "benda" },
  { char: "カップ", romaji: "kappu", meaning: "cangkir", type: "benda" },
  { char: "家庭 (かてい)", romaji: "katei", meaning: "rumah tangga", type: "benda" },
  { char: "角 (かど)", romaji: "kado", meaning: "sudut/belokan", type: "benda" },
  { char: "鞄 (かばん)", romaji: "kaban", meaning: "tas", type: "benda" },
  { char: "花瓶 (かびん)", romaji: "kabin", meaning: "vas bunga", type: "benda" },
  { char: "紙 (かみ)", romaji: "kami", meaning: "kertas", type: "benda" },
  { char: "カメラ", romaji: "kamera", meaning: "kamera", type: "benda" },
  { char: "火曜日 (かようび)", romaji: "kayoubi", meaning: "selasa", type: "benda" },
  { char: "辛い (からい)", romaji: "karai", meaning: "pedas", type: "sifat" },
  { char: "体 (からだ)", romaji: "karada", meaning: "tubuh", type: "benda" },
  { char: "借りる (かりる)", romaji: "kariru", meaning: "meminjam", type: "kerja" },
  { char: "軽い (かるい)", romaji: "karui", meaning: "ringan", type: "sifat" },
  { char: "カレンダー", romaji: "karenda-", meaning: "kalender", type: "benda" },
  { char: "カレー", romaji: "kare-", meaning: "kari", type: "benda" },
  { char: "川 (かわ)", romaji: "kawa", meaning: "sungai", type: "benda" },
  { char: "可愛い (かわいい)", romaji: "kawaii", meaning: "lucu, imut", type: "sifat" },
  { char: "漢字 (かんじ)", romaji: "kanji", meaning: "kanji", type: "benda" },
  { char: "外国 (がいこく)", romaji: "gaikoku", meaning: "luar negeri", type: "benda" },
  { char: "学生 (がくせい)", romaji: "gakusei", meaning: "siswa", type: "benda" },
  { char: "学校 (がっこう)", romaji: "gakkou", meaning: "sekolah", type: "benda" },
  { char: "木 (き)", romaji: "ki", meaning: "pohon", type: "benda" },
  { char: "黄色 (きいろ)", romaji: "kiiro", meaning: "kuning", type: "benda" },
  { char: "黄色い (きいろい)", romaji: "kiiroi", meaning: "kuning", type: "sifat" },
  { char: "消える (きえる)", romaji: "kieru", meaning: "padam/hilang", type: "kerja" },
  { char: "聞く (きく)", romaji: "kiku", meaning: "mendengar", type: "kerja" },
  { char: "北 (きた)", romaji: "kita", meaning: "utara", type: "benda" },
  { char: "汚い (きたない)", romaji: "kitanai", meaning: "kotor", type: "sifat" },
  { char: "喫茶店 (きっさてん)", romaji: "kissaten", meaning: "kedai kopi", type: "benda" },
  { char: "切手 (きって)", romaji: "kitte", meaning: "perangko", type: "benda" },
  { char: "切符 (きっぷ)", romaji: "kippu", meaning: "tiket", type: "benda" },
  { char: "昨日 (きのう)", romaji: "kinou", meaning: "kemarin", type: "keterangan" },
  { char: "今日 (きょう)", romaji: "kyou", meaning: "hari ini", type: "keterangan" },
  { char: "教室 (きょうしつ)", romaji: "kyoushitsu", meaning: "ruang kelas", type: "benda" },
  { char: "兄弟 (きょうだい)", romaji: "kyoudai", meaning: "saudara", type: "benda" },
  { char: "去年 (きょねん)", romaji: "kyonen", meaning: "tahun lalu", type: "keterangan" },
  { char: "嫌い (きらい)", romaji: "kirai", meaning: "benci/tidak suka", type: "sifat" },
  { char: "切る (きる)", romaji: "kiru", meaning: "memotong", type: "kerja" },
  { char: "着る (きる)", romaji: "kiru", meaning: "memakai (baju)", type: "kerja" },
  { char: "綺麗 (きれい)", romaji: "kirei", meaning: "cantik/bersih", type: "sifat" },
  { char: "銀行 (ぎんこう)", romaji: "ginkou", meaning: "bank", type: "benda" },
  { char: "薬 (くすり)", romaji: "kusuri", meaning: "obat", type: "benda" },
  { char: "果物 (くだもの)", romaji: "kudamono", meaning: "buah", type: "benda" },
  { char: "口 (くち)", romaji: "kuchi", meaning: "mulut", type: "benda" },
  { char: "靴 (くつ)", romaji: "kutsu", meaning: "sepatu", type: "benda" },
  { char: "靴下 (くつした)", romaji: "kutsushita", meaning: "kaos kaki", type: "benda" },
  { char: "国 (くに)", romaji: "kuni", meaning: "negara", type: "benda" },
  { char: "曇り (くもり)", romaji: "kumori", meaning: "mendung", type: "benda" },
  { char: "暗い (くらい)", romaji: "kurai", meaning: "gelap", type: "sifat" },
  { char: "来る (くる)", romaji: "kuru", meaning: "datang", type: "kerja" },
  { char: "車 (くるま)", romaji: "kuruma", meaning: "mobil", type: "benda" },
  { char: "黒い (くろい)", romaji: "kuroi", meaning: "hitam", type: "sifat" },
  { char: "警官 (けいかん)", romaji: "keikan", meaning: "polisi", type: "benda" },
  { char: "今朝 (けさ)", romaji: "kesa", meaning: "pagi ini", type: "keterangan" },
  { char: "消す (けす)", romaji: "kesu", meaning: "mematikan/menghapus", type: "kerja" },
  { char: "結構 (けっこう)", romaji: "kekkou", meaning: "cukup/lumayan", type: "sifat" },
  { char: "結婚 (けっこん)", romaji: "kekkon", meaning: "menikah", type: "kerja" },
  { char: "月曜日 (げつようび)", romaji: "getsuyoubi", meaning: "senin", type: "benda" },
  { char: "元気 (げんき)", romaji: "genki", meaning: "sehat", type: "sifat" },
  { char: "公園 (こうえん)", romaji: "kouen", meaning: "taman", type: "benda" },
  { char: "交差点 (こうさてん)", romaji: "kousaten", meaning: "perempatan", type: "benda" },
  { char: "紅茶 (こうちゃ)", romaji: "koucha", meaning: "teh hitam", type: "benda" },
  { char: "交番 (こうばん)", romaji: "kouban", meaning: "pos polisi", type: "benda" },
  { char: "声 (こえ)", romaji: "koe", meaning: "suara", type: "benda" },
  { char: "九日 (ここのか)", romaji: "kokonoka", meaning: "tanggal 9", type: "benda" },
  { char: "答える (こたえる)", romaji: "kotaeru", meaning: "menjawab", type: "kerja" },
  { char: "今年 (ことし)", romaji: "kotoshi", meaning: "tahun ini", type: "keterangan" },
  { char: "言葉 (ことば)", romaji: "kotoba", meaning: "kata/bahasa", type: "benda" },
  { char: "子供 (こども)", romaji: "kodomo", meaning: "anak", type: "benda" },
  { char: "コピー", romaji: "kopi-", meaning: "fotokopi", type: "kerja" },
  { char: "困る (こまる)", romaji: "komaru", meaning: "susah/repot", type: "kerja" },
  { char: "今月 (こんげつ)", romaji: "kongetsu", meaning: "bulan ini", type: "keterangan" },
  { char: "今週 (こんしゅう)", romaji: "konshuu", meaning: "minggu ini", type: "keterangan" },
  { char: "今晩 (こんばん)", romaji: "konban", meaning: "malam ini", type: "keterangan" },
  { char: "コーヒー", romaji: "ko-hi-", meaning: "kopi", type: "benda" },
  { char: "午後 (ごご)", romaji: "gogo", meaning: "p.m./sore", type: "benda" },
  { char: "午前 (ごぜん)", romaji: "gozen", meaning: "a.m./pagi", type: "benda" },
  { char: "ご飯 (ごはん)", romaji: "gohan", meaning: "nasi/makan", type: "benda" },
  { char: "財布 (さいふ)", romaji: "saifu", meaning: "dompet", type: "benda" },
  { char: "魚 (さかな)", romaji: "sakana", meaning: "ikan", type: "benda" },
  { char: "先 (さき)", romaji: "saki", meaning: "tadi/duluan", type: "keterangan" },
  { char: "咲く (さく)", romaji: "saku", meaning: "mekar", type: "kerja" },
  { char: "作文 (さくぶん)", romaji: "sakubun", meaning: "karangan", type: "benda" },
  { char: "砂糖 (さとう)", romaji: "satou", meaning: "gula", type: "benda" },
  { char: "寒い (さむい)", romaji: "samui", meaning: "dingin (udara)", type: "sifat" },
  { char: "再来年 (さらいねん)", romaji: "sarainen", meaning: "2 tahun lagi", type: "keterangan" },
  { char: "散歩 (さんぽ)", romaji: "sanpo", meaning: "jalan-jalan", type: "kerja" },
  { char: "雑誌 (ざっし)", romaji: "zasshi", meaning: "majalah", type: "benda" },
  { char: "塩 (しお)", romaji: "shio", meaning: "garam", type: "benda" },
  { char: "しかし", romaji: "shikashi", meaning: "tetapi", type: "penghubung" },
  { char: "仕事 (しごと)", romaji: "shigoto", meaning: "pekerjaan", type: "benda" },
  { char: "下 (した)", romaji: "shita", meaning: "bawah", type: "benda" },
  { char: "質問 (しつもん)", romaji: "shitsumon", meaning: "pertanyaan", type: "benda" },
  { char: "死ぬ (しぬ)", romaji: "shinu", meaning: "mati", type: "kerja" },
  { char: "閉まる (しまる)", romaji: "shimaru", meaning: "tertutup", type: "kerja" },
  { char: "閉める (しめる)", romaji: "shimeru", meaning: "menutup", type: "kerja" },
  { char: "写真 (しゃしん)", romaji: "shashin", meaning: "foto", type: "benda" },
  { char: "シャツ", romaji: "shatsu", meaning: "kemeja", type: "benda" },
  { char: "シャワー", romaji: "shawa-", meaning: "shower", type: "benda" },
  { char: "宿題 (しゅくだい)", romaji: "shukudai", meaning: "PR", type: "benda" },
  { char: "醤油 (しょうゆ)", romaji: "shouyu", meaning: "kecap asin", type: "benda" },
  { char: "食堂 (しょくどう)", romaji: "shokudou", meaning: "kantin", type: "benda" },
  { char: "知る (しる)", romaji: "shiru", meaning: "tahu", type: "kerja" },
  { char: "白い (しろい)", romaji: "shiroi", meaning: "putih", type: "sifat" },
  { char: "新聞 (しんぶん)", romaji: "shinbun", meaning: "koran", type: "benda" },
  { char: "時間 (じかん)", romaji: "jikan", meaning: "waktu", type: "benda" },
  { char: "辞書 (じしょ)", romaji: "jisho", meaning: "kamus", type: "benda" },
  { char: "自転車 (じてんしゃ)", romaji: "jitensha", meaning: "sepeda", type: "benda" },
  { char: "自動車 (jidousha)", romaji: "jidousha", meaning: "mobil", type: "benda" },
  { char: "自分 (じぶん)", romaji: "jibun", meaning: "diri sendiri", type: "benda" },
  { char: "授業 (じゅぎょう)", romaji: "jugyou", meaning: "pelajaran", type: "benda" },
  { char: "上手 (じょうず)", romaji: "jouzu", meaning: "mahir", type: "sifat" },
  { char: "丈夫 (じょうぶ)", romaji: "joubu", meaning: "kuat/kokoh", type: "sifat" },
  { char: "吸う (すう)", romaji: "suu", meaning: "merokok/menghisap", type: "kerja" },
  { char: "スカート", romaji: "suka-to", meaning: "rok", type: "benda" },
  { char: "好き (すき)", romaji: "suki", meaning: "suka", type: "sifat" },
  { char: "少ない (すくない)", romaji: "sukunai", meaning: "sedikit", type: "sifat" },
  { char: "少し (すこし)", romaji: "sukoshi", meaning: "sedikit", type: "keterangan" },
  { char: "涼しい (すずしい)", romaji: "suzushii", meaning: "sejuk", type: "sifat" },
  { char: "住む (すむ)", romaji: "sumu", meaning: "tinggal", type: "kerja" },
  { char: "スリッパ", romaji: "surippa", meaning: "sandal", type: "benda" },
  { char: "座る (すわる)", romaji: "suwaru", meaning: "duduk", type: "kerja" },
  { char: "狭い (せまい)", romaji: "semai", meaning: "sempit", type: "sifat" },
  { char: "先月 (せんげつ)", romaji: "sengetsu", meaning: "bulan lalu", type: "keterangan" },
  { char: "先週 (せんしゅう)", romaji: "senshuu", meaning: "minggu lalu", type: "keterangan" },
  { char: "先生 (せんせい)", romaji: "sensei", meaning: "guru", type: "benda" },
  { char: "洗濯 (せんたく)", romaji: "sentaku", meaning: "mencuci baju", type: "kerja" },
  { char: "全部 (ぜんぶ)", romaji: "zenbu", meaning: "semua", type: "keterangan" },
  { char: "掃除 (そうじ)", romaji: "souji", meaning: "bersih-bersih", type: "kerja" },
  { char: "外 (そと)", romaji: "soto", meaning: "luar", type: "benda" },
  { char: "空 (そら)", romaji: "sora", meaning: "langit", type: "benda" },
  { char: "大切 (たいせつ)", romaji: "taisetsu", meaning: "penting", type: "sifat" },
  { char: "大変 (たいへん)", romaji: "taihen", meaning: "berat/sulit", type: "sifat" },
  { char: "高い (たかい)", romaji: "takai", meaning: "tinggi/mahal", type: "sifat" },
  { char: "たくさん", romaji: "takusan", meaning: "banyak", type: "keterangan" },
  { char: "タクシー", romaji: "takushi-", meaning: "taksi", type: "benda" },
  { char: "立つ (たつ)", romaji: "tatsu", meaning: "berdiri", type: "kerja" },
  { char: "建物 (たてもの)", romaji: "tatemono", meaning: "bangunan", type: "benda" },
  { char: "楽しい (tanoshii)", romaji: "tanoshii", meaning: "menyenangkan", type: "sifat" },
  { char: "頼む (たのむ)", romaji: "tanomu", meaning: "meminta", type: "kerja" },
  { char: "食べ物 (たべもの)", romaji: "tabemono", meaning: "makanan", type: "benda" },
  { char: "食べる (たべる)", romaji: "taberu", meaning: "makan", type: "kerja" },
  { char: "卵 (たまご)", romaji: "tamago", meaning: "telur", type: "benda" },
  { char: "誕生日 (たんじょうび)", romaji: "tanjoubi", meaning: "ulang tahun", type: "benda" },
  { char: "大丈夫 (だいじょうぶ)", romaji: "daijoubu", meaning: "tidak apa-apa", type: "sifat" },
  { char: "大好き (だいすき)", romaji: "daisuki", meaning: "sangat suka", type: "sifat" },
  { char: "台所 (だいどころ)", romaji: "daidokoro", meaning: "dapur", type: "benda" },
  { char: "出す (だす)", romaji: "dasu", meaning: "mengeluarkan", type: "kerja" },
  { char: "小さい (ちいさい)", romaji: "chiisai", meaning: "kecil", type: "sifat" },
  { char: "近い (ちかい)", romaji: "chikai", meaning: "dekat", type: "sifat" },
  { char: "地下鉄 (ちかてつ)", romaji: "chikatetsu", meaning: "kereta bawah tanah", type: "benda" },
  { char: "地図 (ちず)", romaji: "chizu", meaning: "peta", type: "benda" },
  { char: "使う (つかう)", romaji: "tsukau", meaning: "menggunakan", type: "kerja" },
  { char: "疲れる (つかれる)", romaji: "tsukareru", meaning: "lelah", type: "kerja" },
  { char: "次 (つぎ)", romaji: "tsugi", meaning: "selanjutnya", type: "benda" },
  { char: "着く (つく)", romaji: "tsuku", meaning: "tiba", type: "kerja" },
  { char: "机 (つくえ)", romaji: "tsukue", meaning: "meja", type: "benda" },
  { char: "作る (つくる)", romaji: "tsukuru", meaning: "membuat", type: "kerja" },
  { char: "強い (つよい)", romaji: "tsuyoi", meaning: "kuat", type: "sifat" },
  { char: "手紙 (てがみ)", romaji: "tegami", meaning: "surat", type: "benda" },
  { char: "出口 (でぐち)", romaji: "deguchi", meaning: "pintu keluar", type: "benda" },
  { char: "テスト", romaji: "tesuto", meaning: "tes", type: "benda" },
  { char: "電車 (でんしゃ)", romaji: "densha", meaning: "kereta", type: "benda" },
  { char: "電話 (でんわ)", romaji: "denwa", meaning: "telepon", type: "kerja" },
  { char: "遠い (とおい)", romaji: "tooi", meaning: "jauh", type: "sifat" },
  { char: "時々 (ときどき)", romaji: "tokidoki", meaning: "kadang-kadang", type: "keterangan" },
  { char: "時計 (とけい)", romaji: "tokei", meaning: "jam", type: "benda" },
  { char: "図書館 (としょかん)", romaji: "toshokan", meaning: "perpustakaan", type: "benda" },
  { char: "とても", romaji: "totemo", meaning: "sangat", type: "keterangan" },
  { char: "止まる (とまる)", romaji: "tomaru", meaning: "berhenti", type: "kerja" },
  { char: "友達 (ともだち)", romaji: "tomodachi", meaning: "teman", type: "benda" },
  { char: "取る (とる)", romaji: "toru", meaning: "mengambil", type: "kerja" },
  { char: "撮る (とる)", romaji: "toru", meaning: "memotret", type: "kerja" },
  { char: "動物 (どうぶつ)", romaji: "doubutsu", meaning: "hewan", type: "benda" },
  { char: "土曜日 (どようび)", romaji: "doyoubi", meaning: "sabtu", type: "benda" },
  { char: "中 (なか)", romaji: "naka", meaning: "dalam", type: "benda" },
  { char: "長い (ながい)", romaji: "nagai", meaning: "panjang", type: "sifat" },
  { char: "夏休み (なつやすみ)", romaji: "natsuyasumi", meaning: "libur musim panas", type: "benda" },
  { char: "名前 (なまえ)", romaji: "namae", meaning: "nama", type: "benda" },
  { char: "習う (ならう)", romaji: "narau", meaning: "belajar", type: "kerja" },
  { char: "賑やか (にぎやか)", romaji: "nigiyaka", meaning: "ramai", type: "sifat" },
  { char: "肉 (にく)", romaji: "niku", meaning: "daging", type: "benda" },
  { char: "西 (にし)", romaji: "nishi", meaning: "barat", type: "benda" },
  { char: "日曜日 (にちようび)", romaji: "nichiyoubi", meaning: "minggu", type: "benda" },
  { char: "荷物 (にもつ)", romaji: "nimotsu", meaning: "barang", type: "benda" },
  { char: "脱ぐ (ぬぐ)", romaji: "nugu", meaning: "melepas baju", type: "kerja" },
  { char: "猫 (ねこ)", romaji: "neko", meaning: "kucing", type: "benda" },
  { char: "寝る (ねる)", romaji: "neru", meaning: "tidur", type: "kerja" },
  { char: "登る (のぼる)", romaji: "noboru", meaning: "mendaki", type: "kerja" },
  { char: "飲み物 (のみもの)", romaji: "nomimono", meaning: "minuman", type: "benda" },
  { char: "飲む (のむ)", romaji: "nomu", meaning: "minum", type: "kerja" },
  { char: "乗る (のる)", romaji: "noru", meaning: "naik kendaraan", type: "kerja" },
  { char: "歯 (は)", romaji: "ha", meaning: "gigi", type: "benda" },
  { char: "入る (はいる)", romaji: "hairu", meaning: "masuk", type: "kerja" },
  { char: "履く (はく)", romaji: "haku", meaning: "memakai (celana/sepatu)", type: "kerja" },
  { char: "箱 (はこ)", romaji: "hako", meaning: "kotak", type: "benda" },
  { char: "橋 (はし)", romaji: "hashi", meaning: "jembatan", type: "benda" },
  { char: "箸 (はし)", romaji: "hashi", meaning: "sumpit", type: "benda" },
  { char: "始まる (はじまる)", romaji: "hajimaru", meaning: "dimulai", type: "kerja" },
  { char: "初めて (はじめて)", romaji: "hajimete", meaning: "pertama kali", type: "keterangan" },
  { char: "働く (はたらく)", romaji: "hataraku", meaning: "bekerja", type: "kerja" },
  { char: "鼻 (はな)", romaji: "hana", meaning: "hidung", type: "benda" },
  { char: "話す (はなす)", romaji: "hanasu", meaning: "berbicara", type: "kerja" },
  { char: "早い (はやい)", romaji: "hayai", meaning: "cepat", type: "sifat" },
  { char: "春 (はる)", romaji: "haru", meaning: "musim semi", type: "benda" },
  { char: "晴れ (はれ)", romaji: "hare", meaning: "cerah", type: "benda" },
  { char: "晩ご飯 (ばんごはん)", romaji: "bangohan", meaning: "makan malam", type: "benda" },
  { char: "パン", romaji: "pan", meaning: "roti", type: "benda" },
  { char: "左 (ひだり)", romaji: "hidari", meaning: "kiri", type: "benda" },
  { char: "人 (ひと)", romaji: "hito", meaning: "orang", type: "benda" },
  { char: "暇 (ひま)", romaji: "hima", meaning: "senggang", type: "sifat" },
  { char: "昼 (ひる)", romaji: "hiru", meaning: "siang", type: "benda" },
  { char: "昼ごはん (ひるごはん)", romaji: "hirugohan", meaning: "makan siang", type: "benda" },
  { char: "広い (ひろい)", romaji: "hiroi", meaning: "luas", type: "sifat" },
  { char: "病院 (びょういん)", romaji: "byouin", meaning: "rumah sakit", type: "benda" },
  { char: "封筒 (ふうとう)", romaji: "fuutou", meaning: "amplop", type: "benda" },
  { char: "太い (ふとい)", romaji: "futoi", meaning: "gemuk/tebal", type: "sifat" },
  { char: "冬 (ふゆ)", romaji: "fuyu", meaning: "musim dingin", type: "benda" },
  { char: "降る (ふる)", romaji: "furu", meaning: "turun (hujan/salju)", type: "kerja" },
  { char: "古い (ふるい)", romaji: "furui", meaning: "tua/lama", type: "sifat" },
  { char: "下手 (へた)", romaji: "heta", meaning: "tidak mahir", type: "sifat" },
  { char: "部屋 (へや)", romaji: "heya", meaning: "kamar", type: "benda" },
  { char: "勉強 (べんきょう)", romaji: "benkyou", meaning: "belajar", type: "kerja" },
  { char: "便利 (べんり)", romaji: "benri", meaning: "praktis", type: "sifat" },
  { char: "本当 (ほんとう)", romaji: "hontou", meaning: "benar", type: "sifat" },
  { char: "本棚 (ほんだな)", romaji: "hondana", meaning: "rak buku", type: "benda" },
  { char: "待つ (まつ)", romaji: "matsu", meaning: "menunggu", type: "kerja" },
  { char: "窓 (まど)", romaji: "mado", meaning: "jendela", type: "benda" },
  { char: "万年筆 (まんねんひつ)", romaji: "mannenhitsu", meaning: "pulpen", type: "benda" },
  { char: "磨く (みがく)", romaji: "migaku", meaning: "menggosok", type: "kerja" },
  { char: "右 (みぎ)", romaji: "migi", meaning: "kanan", type: "benda" },
  { char: "短い (みじかい)", romaji: "mijikai", meaning: "pendek", type: "sifat" },
  { char: "店 (みせ)", romaji: "mise", meaning: "toko", type: "benda" },
  { char: "見せる (みせる)", romaji: "miseru", meaning: "memperlihatkan", type: "kerja" },
  { char: "道 (みち)", romaji: "michi", meaning: "jalan", type: "benda" },
  { char: "見る (みる)", romaji: "miru", meaning: "melihat", type: "kerja" },
  { char: "難しい (むずかしい)", romaji: "muzukashii", meaning: "sulit", type: "sifat" },
  { char: "眼鏡 (めがね)", romaji: "megane", meaning: "kacamata", type: "benda" },
  { char: "持ち物 (もちもの)", romaji: "mochimono", meaning: "membawa", type: "kerja" },
  { char: "安い (やすい)", romaji: "yasui", meaning: "murah", type: "sifat" },
  { char: "休み (やすみ)", romaji: "yasumi", meaning: "libur/istirahat", type: "benda" },
  { char: "休む (やすむ)", romaji: "yasumu", meaning: "beristirahat", type: "kerja" },
  { char: "有名 (ゆうめい)", romaji: "yuumei", meaning: "terkenal", type: "sifat" },
  { char: "ゆっくり", romaji: "yukkuri", meaning: "pelan-pelan", type: "keterangan" },
  { char: "洋服 (ようふく)", romaji: "youfuku", meaning: "baju barat", type: "benda" },
  { char: "読む (よむ)", romaji: "yomu", meaning: "membaca", type: "kerja" },
  { char: "弱い (よわい)", romaji: "yowai", meaning: "lemah", type: "sifat" },
  { char: "料理 (りょうり)", romaji: "ryouri", meaning: "masakan", type: "benda" },
  { char: "旅行 (りょこう)", romaji: "ryokou", meaning: "wisata", type: "kerja" },
  { char: "練習 (れんしゅう)", romaji: "renshuu", meaning: "latihan", type: "kerja" },
  { char: "分る (わかる)", romaji: "wakaru", meaning: "mengerti", type: "kerja" },
  { char: "忘れる (わすれる)", romaji: "wasureru", meaning: "lupa", type: "kerja" },
  { char: "悪い (わるい)", romaji: "warui", meaning: "buruk", type: "sifat" },
  { char: "～回 (～かい)", romaji: "kai", meaning: "kali (frekuensi)", type: "bilangan" },
  { char: "～階 (～かい)", romaji: "kai", meaning: "lantai", type: "bilangan" },
  { char: "～ヶ月 (～かげつ)", romaji: "kagetsu", meaning: "bulan (durasi)", type: "bilangan" },
  { char: "～歳 (～さい)", romaji: "sai", meaning: "tahun (umur)", type: "bilangan" },
  { char: "～時 (～じ)", romaji: "ji", meaning: "jam", type: "bilangan" },
  { char: "～人 (～にん)", romaji: "nin", meaning: "orang (jumlah)", type: "bilangan" },
  { char: "～ずつ", romaji: "zutsu", meaning: "setiap/masing-masing", type: "keterangan" },
  { char: "～台 (～だい)", romaji: "dai", meaning: "unit (mesin)", type: "bilangan" },
  { char: "～冊 (～さつ)", romaji: "satsu", meaning: "jilid/buku", type: "bilangan" },
  { char: "～枚 (～まい)", romaji: "mai", meaning: "lembar", type: "bilangan" },
  { char: "～本 (～ほん)", romaji: "hon", meaning: "batang/buah", type: "bilangan" },
  { char: "～分 (～ふん)", romaji: "fun", meaning: "menit", type: "bilangan" },
  { char: "東京 (とうきょう)", romaji: "toukyou", meaning: "Tokyo", type: "benda" },
  { char: "ラーメン", romaji: "ra-men", meaning: "mie ramen", type: "benda" }
];