// src/data.ts
export interface Kana {
  char: string;
  romaji: string;
  type: 'hiragana' | 'katakana';
}

export interface Kanji {
  char: string;
  onyomi: string;
  kunyomi: string;
  meaning: string;
  type: 'kanji';
  level: 'N5' | 'N4' | 'N3' | 'N2' | 'N1';
}

export interface Kotoba {
  char: string; // Dalam Hiragana
  romaji: string;
  meaning: string; // Arti Indonesia
  type: 'benda' | 'kerja' | 'sifat' | 'keterangan' | 'tanya' | 'percakapan' | 'seru' | 'penghubung';
}

export const kanaData: Kana[] = [
  // --- HIRAGANA ---
  // Basic (Seion) 
  { char: 'あ', romaji: 'a', type: 'hiragana' }, { char: 'い', romaji: 'i', type: 'hiragana' },
  { char: 'う', romaji: 'u', type: 'hiragana' }, { char: 'え', romaji: 'e', type: 'hiragana' },
  { char: 'お', romaji: 'o', type: 'hiragana' }, { char: 'か', romaji: 'ka', type: 'hiragana' },
  { char: 'き', romaji: 'ki', type: 'hiragana' }, { char: 'く', romaji: 'ku', type: 'hiragana' },
  { char: 'け', romaji: 'ke', type: 'hiragana' }, { char: 'こ', romaji: 'ko', type: 'hiragana' },
  { char: 'さ', romaji: 'sa', type: 'hiragana' }, { char: 'し', romaji: 'shi', type: 'hiragana' },
  { char: 'す', romaji: 'su', type: 'hiragana' }, { char: 'せ', romaji: 'se', type: 'hiragana' },
  { char: 'そ', romaji: 'so', type: 'hiragana' }, { char: 'た', romaji: 'ta', type: 'hiragana' },
  { char: 'ち', romaji: 'chi', type: 'hiragana' }, { char: 'つ', romaji: 'tsu', type: 'hiragana' },
  { char: 'て', romaji: 'te', type: 'hiragana' }, { char: 'と', romaji: 'to', type: 'hiragana' },
  { char: 'な', romaji: 'na', type: 'hiragana' }, { char: 'に', romaji: 'ni', type: 'hiragana' },
  { char: 'ぬ', romaji: 'nu', type: 'hiragana' }, { char: 'ね', romaji: 'ne', type: 'hiragana' },
  { char: 'の', romaji: 'no', type: 'hiragana' }, { char: 'は', romaji: 'ha', type: 'hiragana' },
  { char: 'ひ', romaji: 'hi', type: 'hiragana' }, { char: 'ふ', romaji: 'fu', type: 'hiragana' },
  { char: 'へ', romaji: 'he', type: 'hiragana' }, { char: 'ほ', romaji: 'ho', type: 'hiragana' },
  { char: 'ま', romaji: 'ma', type: 'hiragana' }, { char: 'み', romaji: 'mi', type: 'hiragana' },
  { char: 'む', romaji: 'mu', type: 'hiragana' }, { char: 'め', romaji: 'me', type: 'hiragana' },
  { char: 'も', romaji: 'mo', type: 'hiragana' }, { char: 'や', romaji: 'ya', type: 'hiragana' },
  { char: 'ゆ', romaji: 'yu', type: 'hiragana' }, { char: 'よ', romaji: 'yo', type: 'hiragana' },
  { char: 'ら', romaji: 'ra', type: 'hiragana' }, { char: 'り', romaji: 'ri', type: 'hiragana' },
  { char: 'る', romaji: 'ru', type: 'hiragana' }, { char: 'れ', romaji: 're', type: 'hiragana' },
  { char: 'ろ', romaji: 'ro', type: 'hiragana' }, { char: 'わ', romaji: 'wa', type: 'hiragana' },
  { char: 'を', romaji: 'wo', type: 'hiragana' }, { char: 'ん', romaji: 'n', type: 'hiragana' },

  // Voiced (Dakuon) 
  { char: 'が', romaji: 'ga', type: 'hiragana' }, { char: 'ぎ', romaji: 'gi', type: 'hiragana' },
  { char: 'ぐ', romaji: 'gu', type: 'hiragana' }, { char: 'げ', romaji: 'ge', type: 'hiragana' },
  { char: 'ご', romaji: 'go', type: 'hiragana' }, { char: 'ざ', romaji: 'za', type: 'hiragana' },
  { char: 'じ', romaji: 'ji', type: 'hiragana' }, { char: 'ず', romaji: 'zu', type: 'hiragana' },
  { char: 'ぜ', romaji: 'ze', type: 'hiragana' }, { char: 'ぞ', romaji: 'zo', type: 'hiragana' },
  { char: 'だ', romaji: 'da', type: 'hiragana' }, { char: 'ぢ', romaji: 'ji', type: 'hiragana' },
  { char: 'づ', romaji: 'zu', type: 'hiragana' }, { char: 'で', romaji: 'de', type: 'hiragana' },
  { char: 'ど', romaji: 'do', type: 'hiragana' }, { char: 'ば', romaji: 'ba', type: 'hiragana' },
  { char: 'び', romaji: 'bi', type: 'hiragana' }, { char: 'ぶ', romaji: 'bu', type: 'hiragana' },
  { char: 'べ', romaji: 'be', type: 'hiragana' }, { char: 'ぼ', romaji: 'bo', type: 'hiragana' },

  // P-Sounds (Handakuon) 
  { char: 'ぱ', romaji: 'pa', type: 'hiragana' }, { char: 'ぴ', romaji: 'pi', type: 'hiragana' },
  { char: 'ぷ', romaji: 'pu', type: 'hiragana' }, { char: 'ぺ', romaji: 'pe', type: 'hiragana' },
  { char: 'ぽ', romaji: 'po', type: 'hiragana' },

  // Yoon (Contracted Syllables) 
  { char: 'きゃ', romaji: 'kya', type: 'hiragana' }, { char: 'きゅ', romaji: 'kyu', type: 'hiragana' }, { char: 'きょ', romaji: 'kyo', type: 'hiragana' },
  { char: 'しゃ', romaji: 'sha', type: 'hiragana' }, { char: 'しゅ', romaji: 'shu', type: 'hiragana' }, { char: 'しょ', romaji: 'sho', type: 'hiragana' },
  { char: 'ちゃ', romaji: 'cha', type: 'hiragana' }, { char: 'ちゅ', romaji: 'chu', type: 'hiragana' }, { char: 'ちょ', romaji: 'cho', type: 'hiragana' },
  { char: 'にゃ', romaji: 'nya', type: 'hiragana' }, { char: 'にゅ', romaji: 'nyu', type: 'hiragana' }, { char: 'にょ', romaji: 'nyo', type: 'hiragana' },
  { char: 'ひゃ', romaji: 'hya', type: 'hiragana' }, { char: 'ひゅ', romaji: 'hyu', type: 'hiragana' }, { char: 'ひょ', romaji: 'hyo', type: 'hiragana' },
  { char: 'みゃ', romaji: 'mya', type: 'hiragana' }, { char: 'みゅ', romaji: 'myu', type: 'hiragana' }, { char: 'みょ', romaji: 'myo', type: 'hiragana' },
  { char: 'りゃ', romaji: 'rya', type: 'hiragana' }, { char: 'りゅ', romaji: 'ryu', type: 'hiragana' }, { char: 'りょ', romaji: 'ryo', type: 'hiragana' },
  { char: 'ぎゃ', romaji: 'gya', type: 'hiragana' }, { char: 'ぎゅ', romaji: 'gyu', type: 'hiragana' }, { char: 'ぎょ', romaji: 'gyo', type: 'hiragana' },
  { char: 'じゃ', romaji: 'ja', type: 'hiragana' }, { char: 'じゅ', romaji: 'ju', type: 'hiragana' }, { char: 'じょ', romaji: 'jo', type: 'hiragana' },
  { char: 'びゃ', romaji: 'bya', type: 'hiragana' }, { char: 'びゅ', romaji: 'byu', type: 'hiragana' }, { char: 'びょ', romaji: 'byo', type: 'hiragana' },
  { char: 'ぴゃ', romaji: 'pya', type: 'hiragana' }, { char: 'ぴゅ', romaji: 'pyu', type: 'hiragana' }, { char: 'ぴょ', romaji: 'pyo', type: 'hiragana' },

  // --- KATAKANA ---
  // Basic (Seion) 
  { char: 'ア', romaji: 'a', type: 'katakana' }, { char: 'イ', romaji: 'i', type: 'katakana' },
  { char: 'ウ', romaji: 'u', type: 'katakana' }, { char: 'エ', romaji: 'e', type: 'katakana' },
  { char: 'オ', romaji: 'o', type: 'katakana' }, { char: 'カ', romaji: 'ka', type: 'katakana' },
  { char: 'キ', romaji: 'ki', type: 'katakana' }, { char: 'ク', romaji: 'ku', type: 'katakana' },
  { char: 'ケ', romaji: 'ke', type: 'katakana' }, { char: 'コ', romaji: 'ko', type: 'katakana' },
  { char: 'サ', romaji: 'sa', type: 'katakana' }, { char: 'シ', romaji: 'shi', type: 'katakana' },
  { char: 'ス', romaji: 'su', type: 'katakana' }, { char: 'セ', romaji: 'se', type: 'katakana' },
  { char: 'ソ', romaji: 'so', type: 'katakana' }, { char: 'タ', romaji: 'ta', type: 'katakana' },
  { char: 'チ', romaji: 'chi', type: 'katakana' }, { char: 'ツ', romaji: 'tsu', type: 'katakana' },
  { char: 'テ', romaji: 'te', type: 'katakana' }, { char: 'ト', romaji: 'to', type: 'katakana' },
  { char: 'ナ', romaji: 'na', type: 'katakana' }, { char: 'ニ', romaji: 'ni', type: 'katakana' },
  { char: 'ヌ', romaji: 'nu', type: 'katakana' }, { char: 'ネ', romaji: 'ne', type: 'katakana' },
  { char: 'ノ', romaji: 'no', type: 'katakana' }, { char: 'ハ', romaji: 'ha', type: 'katakana' },
  { char: 'ヒ', romaji: 'hi', type: 'katakana' }, { char: 'フ', romaji: 'fu', type: 'katakana' },
  { char: 'ヘ', romaji: 'he', type: 'katakana' }, { char: 'ホ', romaji: 'ho', type: 'katakana' },
  { char: 'マ', romaji: 'ma', type: 'katakana' }, { char: 'ミ', romaji: 'mi', type: 'katakana' },
  { char: 'ム', romaji: 'mu', type: 'katakana' }, { char: 'メ', romaji: 'me', type: 'katakana' },
  { char: 'モ', romaji: 'mo', type: 'katakana' }, { char: 'ヤ', romaji: 'ya', type: 'katakana' },
  { char: 'ユ', romaji: 'yu', type: 'katakana' }, { char: 'ヨ', romaji: 'yo', type: 'katakana' },
  { char: 'ラ', romaji: 'ra', type: 'katakana' }, { char: 'リ', romaji: 'ri', type: 'katakana' },
  { char: 'ル', romaji: 'ru', type: 'katakana' }, { char: 'レ', romaji: 're', type: 'katakana' },
  { char: 'ロ', romaji: 'ro', type: 'katakana' }, { char: 'ワ', romaji: 'wa', type: 'katakana' },
  { char: 'ヲ', romaji: 'wo', type: 'katakana' }, { char: 'ン', romaji: 'n', type: 'katakana' },

  // Voiced (Dakuon) 
  { char: 'ガ', romaji: 'ga', type: 'katakana' }, { char: 'ギ', romaji: 'gi', type: 'katakana' },
  { char: 'グ', romaji: 'gu', type: 'katakana' }, { char: 'ゲ', romaji: 'ge', type: 'katakana' },
  { char: 'ゴ', romaji: 'go', type: 'katakana' }, { char: 'ザ', romaji: 'za', type: 'katakana' },
  { char: 'ジ', romaji: 'ji', type: 'katakana' }, { char: 'ズ', romaji: 'zu', type: 'katakana' },
  { char: 'ゼ', romaji: 'ze', type: 'katakana' }, { char: 'ゾ', romaji: 'zo', type: 'katakana' },
  { char: 'ダ', romaji: 'da', type: 'katakana' }, { char: 'ヂ', romaji: 'ji', type: 'katakana' },
  { char: 'ヅ', romaji: 'zu', type: 'katakana' }, { char: 'デ', romaji: 'de', type: 'katakana' },
  { char: 'ド', romaji: 'do', type: 'katakana' }, { char: 'バ', romaji: 'ba', type: 'katakana' },
  { char: 'ビ', romaji: 'bi', type: 'katakana' }, { char: 'ブ', romaji: 'bu', type: 'katakana' },
  { char: 'ベ', romaji: 'be', type: 'katakana' }, { char: 'ボ', romaji: 'bo', type: 'katakana' },

  // P-Sounds (Handakuon) 
  { char: 'パ', romaji: 'pa', type: 'katakana' }, { char: 'ピ', romaji: 'pi', type: 'katakana' },
  { char: 'プ', romaji: 'pu', type: 'katakana' }, { char: 'ペ', romaji: 'pe', type: 'katakana' },
  { char: 'ポ', romaji: 'po', type: 'katakana' },

  // Yoon (Contracted Sounds) 
  { char: 'キャ', romaji: 'kya', type: 'katakana' }, { char: 'キュ', romaji: 'kyu', type: 'katakana' }, { char: 'キョ', romaji: 'kyo', type: 'katakana' },
  { char: 'シャ', romaji: 'sha', type: 'katakana' }, { char: 'シュ', romaji: 'shu', type: 'katakana' }, { char: 'ショ', romaji: 'sho', type: 'katakana' },
  { char: 'チャ', romaji: 'cha', type: 'katakana' }, { char: 'チュ', romaji: 'chu', type: 'katakana' }, { char: 'チョ', romaji: 'cho', type: 'katakana' },
  { char: 'ニャ', romaji: 'nya', type: 'katakana' }, { char: 'ニュ', romaji: 'nyu', type: 'katakana' }, { char: 'ニョ', romaji: 'nyo', type: 'katakana' },
  { char: 'ヒャ', romaji: 'hya', type: 'katakana' }, { char: 'ヒュ', romaji: 'hyu', type: 'katakana' }, { char: 'ヒョ', romaji: 'hyo', type: 'katakana' },
  { char: 'ミャ', romaji: 'mya', type: 'katakana' }, { char: 'ミュ', romaji: 'myu', type: 'katakana' }, { char: 'ミョ', romaji: 'myo', type: 'katakana' },
  { char: 'リャ', romaji: 'rya', type: 'katakana' }, { char: 'リュ', romaji: 'ryu', type: 'katakana' }, { char: 'リョ', romaji: 'ryo', type: 'katakana' },
  { char: 'ギャ', romaji: 'gya', type: 'katakana' }, { char: 'ギュ', romaji: 'gyu', type: 'katakana' }, { char: 'ギョ', romaji: 'gyo', type: 'katakana' },
  { char: 'ジャ', romaji: 'ja', type: 'katakana' }, { char: 'ジュ', romaji: 'ju', type: 'katakana' }, { char: 'ジョ', romaji: 'jo', type: 'katakana' },
  { char: 'ビャ', romaji: 'bya', type: 'katakana' }, { char: 'ビュ', romaji: 'byu', type: 'katakana' }, { char: 'ビョ', romaji: 'byo', type: 'katakana' },
  { char: 'ピャ', romaji: 'pya', type: 'katakana' }, { char: 'ピュ', romaji: 'pyu', type: 'katakana' }, { char: 'ピョ', romaji: 'pyo', type: 'katakana' },
];

export const kanjiData: Kanji[] = [
  { char: '一', onyomi: 'ICHI, ITSU', kunyomi: 'hito(tsu)', meaning: 'one', level: 'N5', type: 'kanji' },
  { char: '二', onyomi: 'NI', kunyomi: 'futa(tsu)', meaning: 'two', level: 'N5', type: 'kanji' },
  { char: '三', onyomi: 'SAN', kunyomi: 'mit(tsu)', meaning: 'three', level: 'N5', type: 'kanji' },
  { char: '四', onyomi: 'SHI', kunyomi: 'yot(tsu), yon', meaning: 'four', level: 'N5', type: 'kanji' },
  { char: '五', onyomi: 'GO', kunyomi: 'itsu(tsu)', meaning: 'five', level: 'N5', type: 'kanji' },
  { char: '六', onyomi: 'ROKU', kunyomi: 'mut(tsu)', meaning: 'six', level: 'N5', type: 'kanji' },
  { char: '七', onyomi: 'SHICHI', kunyomi: 'nana(tsu)', meaning: 'seven', level: 'N5', type: 'kanji' },
  { char: '八', onyomi: 'HACHI', kunyomi: 'yat(tsu)', meaning: 'eight', level: 'N5', type: 'kanji' },
  { char: '九', onyomi: 'KYŪ, KU', kunyomi: 'kokono(tsu)', meaning: 'nine', level: 'N5', type: 'kanji' },
  { char: '十', onyomi: 'JŪ', kunyomi: 'tō, to', meaning: 'ten', level: 'N5', type: 'kanji' },
  { char: '百', onyomi: 'HYAKU', kunyomi: '-', meaning: 'hundred', level: 'N5', type: 'kanji' },
  { char: '千', onyomi: 'SEN', kunyomi: 'chi', meaning: 'thousand', level: 'N5', type: 'kanji' },
  { char: '万', onyomi: 'MAN', kunyomi: '-', meaning: 'ten thousand', level: 'N5', type: 'kanji' },
  { char: '水', onyomi: 'SUI', kunyomi: 'mizu', meaning: 'water', level: 'N5', type: 'kanji' },
  { char: '火', onyomi: 'KA', kunyomi: 'hi', meaning: 'fire', level: 'N5', type: 'kanji' },
  { char: '木', onyomi: 'BOKU, MOKU', kunyomi: 'ki', meaning: 'tree, wood', level: 'N5', type: 'kanji' },
  { char: '天', onyomi: 'TEN', kunyomi: 'ame, ama', meaning: 'heaven, sky', level: 'N5', type: 'kanji' },
  { char: '土', onyomi: 'DO, TO', kunyomi: 'tsuchi', meaning: 'soil, earth', level: 'N5', type: 'kanji' },
  { char: '北', onyomi: 'HOKU', kunyomi: 'kita', meaning: 'north', level: 'N5', type: 'kanji' },
  { char: '東', onyomi: 'TŌ', kunyomi: 'higashi', meaning: 'east', level: 'N5', type: 'kanji' },
  { char: '西', onyomi: 'SEI', kunyomi: 'nishi', meaning: 'west', level: 'N5', type: 'kanji' },
  { char: '南', onyomi: 'NAN', kunyomi: 'minami', meaning: 'south', level: 'N5', type: 'kanji' },
  { char: '左', onyomi: 'SA', kunyomi: 'hidari', meaning: 'left', level: 'N5', type: 'kanji' },
  { char: '右', onyomi: 'U, YŪ', kunyomi: 'migi', meaning: 'right', level: 'N5', type: 'kanji' },
  { char: '日', onyomi: 'NICHI, JITSU', kunyomi: 'hi, -bi', meaning: 'day, sun', level: 'N5', type: 'kanji' },
  { char: '月', onyomi: 'GETSU, GATSU', kunyomi: 'tsuki', meaning: 'month, moon', level: 'N5', type: 'kanji' },
  { char: '花', onyomi: 'KA', kunyomi: 'hana', meaning: 'flower', level: 'N5', type: 'kanji' },
  { char: '魚', onyomi: 'GYO', kunyomi: 'sakana', meaning: 'fish', level: 'N5', type: 'kanji' },
  { char: '空', onyomi: 'KŪ', kunyomi: 'sora', meaning: 'sky', level: 'N5', type: 'kanji' },
  { char: '山', onyomi: 'SAN', kunyomi: 'yama', meaning: 'mountain', level: 'N5', type: 'kanji' },
  { char: '川', onyomi: 'SEN', kunyomi: 'kawa', meaning: 'river', level: 'N5', type: 'kanji' },
  { char: '雨', onyomi: 'U', kunyomi: 'ame', meaning: 'rain', level: 'N5', type: 'kanji' },
  { char: '本', onyomi: 'HON', kunyomi: 'moto', meaning: 'book, origin', level: 'N5', type: 'kanji' },
  { char: '目', onyomi: 'MOKU', kunyomi: 'me', meaning: 'eye', level: 'N5', type: 'kanji' },
  { char: '口', onyomi: 'KŌ, KU', kunyomi: 'kuchi', meaning: 'mouth', level: 'N5', type: 'kanji' },
  { char: '耳', onyomi: 'JI', kunyomi: 'mimi', meaning: 'ear', level: 'N5', type: 'kanji' },
  { char: '手', onyomi: 'SHU', kunyomi: 'te', meaning: 'hand', level: 'N5', type: 'kanji' },
  { char: '足', onyomi: 'SOKU', kunyomi: 'ashi', meaning: 'foot, sufficient', level: 'N5', type: 'kanji' },
  { char: '人', onyomi: 'JIN, NIN', kunyomi: 'hito', meaning: 'person', level: 'N5', type: 'kanji' },
  { char: '母', onyomi: 'BO', kunyomi: 'haha', meaning: 'mother', level: 'N5', type: 'kanji' },
  { char: '父', onyomi: 'FU', kunyomi: 'chichi', meaning: 'father', level: 'N5', type: 'kanji' },
  { char: '女', onyomi: 'JO, NYO', kunyomi: 'onna', meaning: 'female', level: 'N5', type: 'kanji' },
  { char: '男', onyomi: 'DAN, NAN', kunyomi: 'otoko', meaning: 'male', level: 'N5', type: 'kanji' },
  { char: '子', onyomi: 'SHI, SU', kunyomi: 'ko', meaning: 'child', level: 'N5', type: 'kanji' },
  { char: '小', onyomi: 'SHŌ', kunyomi: 'chiisa(i), ko', meaning: 'small', level: 'N5', type: 'kanji' },
  { char: '中', onyomi: 'CHŪ', kunyomi: 'naka', meaning: 'middle, inside', level: 'N5', type: 'kanji' },
  { char: '大', onyomi: 'DAI, TAI', kunyomi: 'ō(kii)', meaning: 'big', level: 'N5', type: 'kanji' },
  { char: '上', onyomi: 'JŌ, SHŌ', kunyomi: 'ue, kami, a(geru)', meaning: 'above, up', level: 'N5', type: 'kanji' },
  { char: '下', onyomi: 'GE, KA', kunyomi: 'shita, sa(geru)', meaning: 'below, down', level: 'N5', type: 'kanji' },
  { char: '何', onyomi: 'KA', kunyomi: 'nani', meaning: 'what', level: 'N5', type: 'kanji' },
  { char: '行', onyomi: 'KŌ, GYŌ', kunyomi: 'i(ku)', meaning: 'go', level: 'N5', type: 'kanji' },
  { char: '見', onyomi: 'KEN', kunyomi: 'mi(ru)', meaning: 'see', level: 'N5', type: 'kanji' },
  { char: '言', onyomi: 'GEN, GON', kunyomi: 'i(u)', meaning: 'say, word', level: 'N5', type: 'kanji' },
  { char: '語', onyomi: 'GO', kunyomi: 'kata(ru)', meaning: 'language', level: 'N5', type: 'kanji' },
  { char: '食', onyomi: 'SHOKU', kunyomi: 'ta(beru), ku(u)', meaning: 'eat', level: 'N5', type: 'kanji' },
  { char: '飲', onyomi: 'IN', kunyomi: 'no(mu)', meaning: 'drink', level: 'N5', type: 'kanji' },
  { char: '会', onyomi: 'KAI', kunyomi: 'a(u)', meaning: 'meet', level: 'N5', type: 'kanji' },
  { char: '学', onyomi: 'GAKU', kunyomi: 'mana(bu)', meaning: 'study', level: 'N5', type: 'kanji' },
  { char: '休', onyomi: 'KYŪ', kunyomi: 'yasu(mu)', meaning: 'rest', level: 'N5', type: 'kanji' },
  { char: '买', onyomi: 'BAI', kunyomi: 'ka(u)', meaning: 'buy', level: 'N5', type: 'kanji' },
  { char: '闻', onyomi: 'BUN, MON', kunyomi: 'ki(ku)', meaning: 'hear', level: 'N5', type: 'kanji' },
  { char: '来', onyomi: 'RAI', kunyomi: 'ku(ru)', meaning: 'come', level: 'N5', type: 'kanji' },
  { char: '立', onyomi: 'RITSU', kunyomi: 'ta(tsu)', meaning: 'stand', level: 'N5', type: 'kanji' },
  { char: '生', onyomi: 'SEI, SHŌ', kunyomi: 'i(kiru), u(mareru), nama', meaning: 'life, raw, student', level: 'N5', type: 'kanji' },
  { char: '話', onyomi: 'WA', kunyomi: 'hana(su), hanashi', meaning: 'talk', level: 'N5', type: 'kanji' },
  { char: '出', onyomi: 'SHUTSU', kunyomi: 'de(ru)', meaning: 'exit', level: 'N5', type: 'kanji' },
  { char: '読', onyomi: 'DOKU', kunyomi: 'yo(mu)', meaning: 'read', level: 'N5', type: 'kanji' },
  { char: '入', onyomi: 'NYŪ', kunyomi: 'hai(ru), i(reru)', meaning: 'enter', level: 'N5', type: 'kanji' },
  { char: '書', onyomi: 'SHO', kunyomi: 'ka(ku)', meaning: 'write, book', level: 'N5', type: 'kanji' },
  { char: '後', onyomi: 'GO, KŌ', kunyomi: 'ato, ushi(ro)', meaning: 'after', level: 'N5', type: 'kanji' },
  { char: '古', onyomi: 'KO', kunyomi: 'furu(i)', meaning: 'old', level: 'N5', type: 'kanji' },
  { char: '高', onyomi: 'KŌ', kunyomi: 'taka(i)', meaning: 'high, expensive', level: 'N5', type: 'kanji' },
  { char: '安', onyomi: 'AN', kunyomi: 'yasu(i)', meaning: 'cheap, safe', level: 'N5', type: 'kanji' },
  { char: '多', onyomi: 'TA', kunyomi: 'oo(i)', meaning: 'many', level: 'N5', type: 'kanji' },
  { char: '新', onyomi: 'SHIN', kunyomi: 'atara(shii)', meaning: 'new', level: 'N5', type: 'kanji' },
  { char: '少', onyomi: 'SHŌ', kunyomi: 'suku(nai), suko(shi)', meaning: 'few, little', level: 'N5', type: 'kanji' },
  { char: '長', onyomi: 'CHŌ', kunyomi: 'naga(i)', meaning: 'long', level: 'N5', type: 'kanji' },
  { char: '白', onyomi: 'HAKU, BYAKU', kunyomi: 'shiro(i)', meaning: 'white', level: 'N5', type: 'kanji' },
  { char: '分', onyomi: 'FUN, BUN', kunyomi: 'wa(karu)', meaning: 'minute, understand', level: 'N5', type: 'kanji' },
  { char: '時', onyomi: 'JI', kunyomi: 'toki', meaning: 'time, hour', level: 'N5', type: 'kanji' },
  { char: '間', onyomi: 'KAN, KEN', kunyomi: 'aida, ma', meaning: 'interval', level: 'N5', type: 'kanji' },
  { char: '週', onyomi: 'SHŪ', kunyomi: '-', meaning: 'week', level: 'N5', type: 'kanji' },
  { char: '年', onyomi: 'NEN', kunyomi: 'toshi', meaning: 'year', level: 'N5', type: 'kanji' },
  { char: '今', onyomi: 'KON, KIN', kunyomi: 'ima', meaning: 'now', level: 'N5', type: 'kanji' },
  { char: '先', onyomi: 'SEN', kunyomi: 'saki', meaning: 'previous, ahead', level: 'N5', type: 'kanji' },
  { char: '前', onyomi: 'ZEN', kunyomi: 'mae', meaning: 'before', level: 'N5', type: 'kanji' },
  { char: '午', onyomi: 'GO', kunyomi: '-', meaning: 'noon', level: 'N5', type: 'kanji' },
  { char: '半', onyomi: 'HAN', kunyomi: 'naka(ba)', meaning: 'half', level: 'N5', type: 'kanji' },
  { char: '店', onyomi: 'TEN', kunyomi: 'mise', meaning: 'store', level: 'N5', type: 'kanji' },
  { char: '外', onyomi: 'GAI', kunyomi: 'soto', meaning: 'outside', level: 'N5', type: 'kanji' },
  { char: '電', onyomi: 'DEN', kunyomi: '-', meaning: 'electricity', level: 'N5', type: 'kanji' },
  { char: '道', onyomi: 'DŌ', kunyomi: 'michi', meaning: 'road', level: 'N5', type: 'kanji' },
  { char: '毎', onyomi: 'MAI', kunyomi: '-', meaning: 'every', level: 'N5', type: 'kanji' },
  { char: '友', onyomi: 'YŪ', kunyomi: 'tomo', meaning: 'friend', level: 'N5', type: 'kanji' },
  { char: '名', onyomi: 'MEI, MYŌ', kunyomi: 'na', meaning: 'name', level: 'N5', type: 'kanji' },
  { char: '金', onyomi: 'KIN, KON', kunyomi: 'kane', meaning: 'gold, money, metal', level: 'N5', type: 'kanji' },
  { char: '円', onyomi: 'EN', kunyomi: 'maru(i)', meaning: 'circle, yen', level: 'N5', type: 'kanji' },
  { char: '車', onyomi: 'SHA', kunyomi: 'kuruma', meaning: 'car', level: 'N5', type: 'kanji' },
  { char: '駅', onyomi: 'EKI', kunyomi: '-', meaning: 'station', level: 'N5', type: 'kanji' },
  { char: '気', onyomi: 'KI, KE', kunyomi: '-', meaning: 'spirit, air', level: 'N5', type: 'kanji' },
  { char: '国', onyomi: 'KOKU', kunyomi: 'kuni', meaning: 'country', level: 'N5', type: 'kanji' },
  { char: '社', onyomi: 'SHA', kunyomi: 'yashiro', meaning: 'company, shrine', level: 'N5', type: 'kanji' },
  { char: '校', onyomi: 'KŌ', kunyomi: '-', meaning: 'school', level: 'N5', type: 'kanji' },
];

export const kotobaData: Kotoba[] = [
  // --- PERCAKAPAN DASAR ---
  { char: 'こんにちは', romaji: 'konnichiwa', meaning: 'Halo / Selamat Siang', type: 'percakapan' },
  { char: 'ありがとう', romaji: 'arigatou', meaning: 'Terima Kasih', type: 'percakapan' },
  { char: 'すみません', romaji: 'sumimasen', meaning: 'Maaf / Permisi', type: 'percakapan' },
  { char: 'おはよう', romaji: 'ohayou', meaning: 'Selamat Pagi', type: 'percakapan' },
  { char: 'こんばんは', romaji: 'konbanwa', meaning: 'Selamat Malam', type: 'percakapan' },
  { char: 'さようなら', romaji: 'sayounara', meaning: 'Selamat Tinggal', type: 'percakapan' },
  { char: 'はい', romaji: 'hai', meaning: 'Ya', type: 'percakapan' },
  { char: 'いいえ', romaji: 'iie', meaning: 'Tidak', type: 'percakapan' },

  // --- KATA BENDA (N5) ---
  { char: 'わたし', romaji: 'watashi', meaning: 'Saya', type: 'benda' },
  { char: 'ともだち', romaji: 'tomodachi', meaning: 'Teman', type: 'benda' },
  { char: 'せんせい', romaji: 'sensei', meaning: 'Guru', type: 'benda' },
  { char: 'がくせい', romaji: 'gakusei', meaning: 'Siswa / Mahasiswa', type: 'benda' },
  { char: 'がっこう', romaji: 'gakkou', meaning: 'Sekolah', type: 'benda' },
  { char: 'にほん', romaji: 'nihon', meaning: 'Jepang', type: 'benda' },
  { char: 'ほん', romaji: 'hon', meaning: 'Buku', type: 'benda' },
  { char: 'くるま', romaji: 'kuruma', meaning: 'Mobil', type: 'benda' },
  { char: 'みず', romaji: 'mizu', meaning: 'Air', type: 'benda' },
  { char: 'ごはん', romaji: 'gohan', meaning: 'Nasi / Makan', type: 'benda' },
  { char: 'おうち', romaji: 'ouchi', meaning: 'Rumah', type: 'benda' },
  { char: 'ねこ', romaji: 'neko', meaning: 'Kucing', type: 'benda' },
  { char: 'いぬ', romaji: 'inu', meaning: 'Anjing', type: 'benda' },
  { char: 'かさ', romaji: 'kasa', meaning: 'Payung', type: 'benda' },

  // --- KATA KERJA (N5) ---
  { char: 'たべます', romaji: 'tabemasu', meaning: 'Makan', type: 'kerja' },
  { char: 'のみます', romaji: 'nomimasu', meaning: 'Minum', type: 'kerja' },
  { char: 'いきます', romaji: 'ikimasu', meaning: 'Pergi', type: 'kerja' },
  { char: 'きます', romaji: 'kimasu', meaning: 'Datang', type: 'kerja' },
  { char: 'かえります', romaji: 'kaerimasu', meaning: 'Pulang', type: 'kerja' },
  { char: 'みます', romaji: 'mimasu', meaning: 'Melihat', type: 'kerja' },
  { char: 'ききます', romaji: 'kikimasu', meaning: 'Mendengar', type: 'kerja' },
  { char: 'よみます', romaji: 'yomimasu', meaning: 'Membaca', type: 'kerja' },
  { char: 'かきます', romaji: 'kakimasu', meaning: 'Menulis', type: 'kerja' },
  { char: 'します', romaji: 'shimasu', meaning: 'Melakukan', type: 'kerja' },

  // --- KATA SIFAT (N5) ---
  { char: 'いい', romaji: 'ii', meaning: 'Bagus / Baik', type: 'sifat' },
  { char: 'わるい', romaji: 'warui', meaning: 'Buruk / Jelek', type: 'sifat' },
  { char: 'たかい', romaji: 'takai', meaning: 'Tinggi / Mahal', type: 'sifat' },
  { char: 'やすい', romaji: 'yasui', meaning: 'Murah', type: 'sifat' },
  { char: 'おいしい', romaji: 'oishii', meaning: 'Enak (Makanan)', type: 'sifat' },
  { char: 'おおきい', romaji: 'ookii', meaning: 'Besar', type: 'sifat' },
  { char: 'ちいさい', romaji: 'chiisai', meaning: 'Kecil', type: 'sifat' },
  { char: 'あつい', romaji: 'atsui', meaning: 'Panas', type: 'sifat' },
  { char: 'さむい', romaji: 'samui', meaning: 'Dingin (Cuaca)', type: 'sifat' },

  // --- KATA TANYA ---
  { char: 'なに', romaji: 'nani', meaning: 'Apa', type: 'tanya' },
  { char: 'どこ', romaji: 'doko', meaning: 'Dimana', type: 'tanya' },
  { char: 'だれ', romaji: 'dare', meaning: 'Siapa', type: 'tanya' },
  { char: 'いつ', romaji: 'itsu', meaning: 'Kapan', type: 'tanya' },
  { char: 'どうして', romaji: 'doushite', meaning: 'Kenapa', type: 'tanya' },

  // --- KATA KETERANGAN & PENGHUBUNG ---
  { char: 'とても', romaji: 'totemo', meaning: 'Sangat', type: 'keterangan' },
  { char: 'ちょっと', romaji: 'chotto', meaning: 'Sedikit / Sebentar', type: 'keterangan' },
  { char: 'そして', romaji: 'soshite', meaning: 'Lalu / Dan', type: 'penghubung' },
  { char: 'だから', romaji: 'dakara', meaning: 'Karena itu', type: 'penghubung' },
  { char: 'わあ', romaji: 'waa', meaning: 'Wah! (Kagum)', type: 'seru' },
];